import type { GovernanceCommandV2, GovernanceDocumentV2, GovernanceRoleAssignmentV2, ExternalRoleCatalogSnapshotV1 } from './types'
import type { GovernanceDocumentViewV2 } from './governancePresentation'

export const GOVERNANCE_API_PATH = '/api/orgmaster/governance'
export type GovernanceVersionSummary = { id: string; kind: 'legacy-policy-v1' | 'assignment-governance-v2'; versionNumber: number; publishedAt: string; publishedByPrincipalId: string; publishReason: string; snapshotHash: string; organizationVersionId: string; effectState: string }
export type GovernanceApiSnapshot = { document: GovernanceDocumentViewV2; catalogs: ExternalRoleCatalogSnapshotV1[]; revision: string; activeVersionId: string | null; versions: GovernanceVersionSummary[] }
export type GovernanceSession = { runtimeMode: string; actor: { principalId: string; subjectHint: string }; capabilities: { manage: boolean; publish: boolean; simulate: boolean } }
export class GovernanceApiError extends Error { constructor(public readonly code: string, public readonly status: number, public readonly issues?: unknown) { super(code) } }
const headers = { 'Content-Type': 'application/json', 'X-OrgMaster-Dev-Issuer': 'urn:orgmaster:dev', 'X-OrgMaster-Dev-Subject': 'local-admin' }
async function request<T>(path: string, init: RequestInit = {}) { const response = await fetch(`${GOVERNANCE_API_PATH}${path}`, { ...init, headers: { ...headers, ...(init.headers ?? {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new GovernanceApiError(payload.error ?? 'GOVERNANCE_REQUEST_FAILED', response.status, payload.issues); return { payload: payload as T, revision: response.headers.get('X-OrgMaster-Governance-Revision') ?? '' } }
export async function loadGovernance() { return request<GovernanceApiSnapshot>('/') }
export async function loadGovernanceSession() { return request<GovernanceSession>('/session') }
export async function patchGovernanceDraft(revision: string, command: GovernanceCommandV2) { return request<{ status: string; document: GovernanceDocumentViewV2; revision: string }>('/draft', { method: 'PATCH', body: JSON.stringify({ expectedRevision: revision, command }) }) }
export async function validateGovernanceAssignment(value: Partial<GovernanceRoleAssignmentV2>) { return request<{ status: 'valid' | 'invalid'; issues: Array<{ code: string; path: string; message: string }>; catalogVersion: string; payloadHash: string; effectState: string; checkedAt: string }>('/validate/assignment', { method: 'POST', body: JSON.stringify(value) }) }
export async function publishGovernancePolicy(revision: string, commandId: string, reason: string, organizationVersionId: string) { return request<{ versionSummary: GovernanceVersionSummary; revision: string }>('/versions', { method: 'POST', body: JSON.stringify({ expectedRevision: revision, commandId, reason, organizationVersionId }) }) }
export async function setActiveGovernanceVersion(revision: string, commandId: string, reason: string, versionId: string | null) { return request<{ activePolicyVersionId: string | null; revision: string }>('/active-version', { method: 'POST', body: JSON.stringify({ expectedRevision: revision, commandId, reason, versionId }) }) }
export async function loadGovernanceVersion(id: string) { return request<{ version: GovernanceDocumentV2['publishedVersions'][number] }>(`/versions/${encodeURIComponent(id)}`) }
export async function loadGovernanceAudit(limit = 50, cursor?: string | null) { return request<{ items: unknown[]; nextCursor: string | null }>(`/audit?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ''}`) }
