import type { GovernanceCommand, GovernanceDocumentV1, PermissionEvaluationRequestV1, PermissionEvaluationResultV1, ReviewerResolutionRequestV1, ReviewerResolutionResultV1 } from './types'
export const GOVERNANCE_API_PATH = '/api/orgmaster/governance'
export type GovernanceApiSnapshot = { document: GovernanceDocumentV1; revision: string; activeVersionId: string | null; versions: Array<{ id: string; versionNumber: number; publishedAt: string; snapshotHash: string; organizationVersionId: string }> }
export class GovernanceApiError extends Error { constructor(public readonly code: string, public readonly status: number, public readonly issues?: unknown) { super(code) } }
const headers = { 'Content-Type': 'application/json', 'X-OrgMaster-Dev-Issuer': 'urn:orgmaster:dev', 'X-OrgMaster-Dev-Subject': 'local-admin' }
async function request<T>(path: string, init: RequestInit = {}) { const response = await fetch(`${GOVERNANCE_API_PATH}${path}`, { ...init, headers: { ...headers, ...(init.headers ?? {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new GovernanceApiError(payload.error ?? 'GOVERNANCE_REQUEST_FAILED', response.status, payload.issues); return { payload: payload as T, revision: response.headers.get('X-OrgMaster-Governance-Revision') ?? '' } }
export async function loadGovernance() { return request<GovernanceApiSnapshot>('/') }
export async function loadGovernanceSession() { return request<{ runtimeMode: string; actor: { principalId: string; subjectHint: string }; capabilities: Record<string, boolean> }>('/session') }
export async function patchGovernanceDraft(revision: string, command: GovernanceCommand) { return request<{ status: string; document: GovernanceDocumentV1; revision: string }>('/draft', { method: 'PATCH', body: JSON.stringify({ expectedRevision: revision, command }) }) }
export async function publishGovernancePolicy(revision: string, commandId: string, reason: string, organizationVersionId: string) { return request<{ versionSummary: { id: string; versionNumber: number }; revision: string }>('/versions', { method: 'POST', body: JSON.stringify({ expectedRevision: revision, commandId, reason, organizationVersionId }) }) }
export async function setActiveGovernanceVersion(revision: string, commandId: string, reason: string, versionId: string | null) { return request<{ activePolicyVersionId: string | null; revision: string }>('/active-version', { method: 'POST', body: JSON.stringify({ expectedRevision: revision, commandId, reason, versionId }) }) }
export async function evaluateGovernancePermission(requestBody: PermissionEvaluationRequestV1) { return request<PermissionEvaluationResultV1>('/evaluate/permission', { method: 'POST', body: JSON.stringify(requestBody) }) }
export async function resolveGovernanceReviewers(requestBody: ReviewerResolutionRequestV1) { return request<ReviewerResolutionResultV1>('/evaluate/reviewers', { method: 'POST', body: JSON.stringify(requestBody) }) }
export async function loadGovernanceAudit(limit = 50, cursor?: string | null) { return request<{ items: unknown[]; nextCursor: string | null }>(`/audit?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ''}`) }
