import { useState } from 'react'
import { X } from 'lucide-react'
import { managementMethodApi, ManagementMethodApiError } from '../../managementMethods/apiClient'
import { plainTextDocument } from '../../managementMethods/pasteSanitizer'
import type { ManagementMethodV1 } from '../../managementMethods/types'

interface Props { onClose: () => void; onCreated: (method: ManagementMethodV1) => void }
export function ManagementMethodCreateDialog({ onClose, onCreated }: Props) {
  const [title, setTitle] = useState(''); const [goal, setGoal] = useState(''); const [facts, setFacts] = useState(''); const [rules, setRules] = useState(''); const [existing, setExisting] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const submit = async () => { if (!goal.trim()) { setError('請先輸入建立目的或已知目標'); return }; setBusy(true); setError(''); try { const result = await managementMethodApi.create({ creationRequestId: crypto.randomUUID(), requestedTitle: title || null, goalAndPurpose: goal, confirmedCurrentFacts: facts, confirmedTargetRules: rules, existingContent: existing.trim() ? { format: 'editor-json-v1', body: plainTextDocument(existing) } : null }); onCreated(result.method) } catch (reason) { setError(reason instanceof ManagementMethodApiError ? `AI 初稿未建立：${reason.failure.code}` : 'AI 初稿未建立') } finally { setBusy(false) } }
  return <div className="management-method-dialog-backdrop" role="presentation"><section className="management-method-create" role="dialog" aria-modal="true" aria-labelledby="management-method-create-title"><header><div><span>新增管理辦法</span><h2 id="management-method-create-title">先提供內容，再產生第一份初稿</h2></div><button type="button" aria-label="關閉" onClick={onClose}><X size={18} /></button></header><div className="management-method-create__body"><label>標題（可選）<input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={120} /></label><label>建立目的／目標<textarea value={goal} onChange={(event) => setGoal(event.target.value)} rows={4} /></label><label>已確認事實（可選）<textarea value={facts} onChange={(event) => setFacts(event.target.value)} rows={4} /></label><label>希望建立的原則或規則（可選）<textarea value={rules} onChange={(event) => setRules(event.target.value)} rows={4} /></label><label>既有內容（可選，貼上後由人類確認）<textarea value={existing} onChange={(event) => setExisting(event.target.value)} rows={5} /></label>{error && <p className="management-method-error" role="alert">{error}</p>}</div><footer><button type="button" className="button-secondary" onClick={onClose}>取消</button><button type="button" className="button-primary" disabled={busy} onClick={() => void submit()}>{busy ? '產生中…' : '產生初稿'}</button></footer></section></div>
}
