import { createHash } from 'node:crypto'
import type { IncomingMessage, ServerResponse } from 'node:http'
import type { Connect, Plugin, PreviewServer, ViteDevServer } from 'vite'
import { z } from 'zod'
import { createInputSchema, collectMediaIds } from '../src/managementMethods/schema'
import type { ManagementMethodCreateInputV1 } from '../src/managementMethods/types'
import { deriveMethodStatus } from '../src/managementMethods/status'
import { capabilityFor, capabilitiesFor, actorFromRequest } from './managementMethodAuthorization'
import { ManagementMethodStoreError, createManagementMethod, getManagementMethodPaths, readManagementMethodStore, restoreDraft, saveDraft, stopReadable, storeRevision, updateMethodMetadata, provideReadable, withStoreMutation } from './managementMethodStore'
import { ManagementMethodMediaError, ingestManagementMethodMedia, readManagementMethodMedia, removeMediaFileIfExists } from './managementMethodMediaStore'
import { ManagementMethodAiError, selectManagementMethodDraftGenerator } from './managementMethodAi'

export const MANAGEMENT_METHOD_API_PATH = '/api/orgmaster/management-methods'
const MAX_BODY = 2 * 1024 * 1024
const inflight = new Map<string, Promise<unknown>>()

function sendJson(response: ServerResponse, status: number, payload: unknown, revision?: string) { response.statusCode = status; response.setHeader('Content-Type', 'application/json; charset=utf-8'); response.setHeader('Cache-Control', 'no-store'); if (revision) response.setHeader('X-OrgMaster-Management-Method-Revision', revision); response.end(JSON.stringify(payload)) }
function readBody(request: IncomingMessage, limit = MAX_BODY) { return new Promise<Buffer>((resolve, reject) => { const chunks: Buffer[] = []; let size = 0; request.on('data', (chunk: Buffer | string) => { const buffer = Buffer.from(chunk); size += buffer.byteLength; if (size > limit) { reject(new ManagementMethodStoreError(limit > MAX_BODY ? 'MEDIA_TOO_LARGE' : 'PAYLOAD_TOO_LARGE')); request.destroy(); return } chunks.push(buffer) }); request.on('end', () => resolve(Buffer.concat(chunks))); request.on('error', reject) }) }
async function jsonBody(request: IncomingMessage) { const contentType = String(request.headers['content-type'] ?? '').toLowerCase(); if (!contentType.startsWith('application/json')) throw new ManagementMethodStoreError('CONTENT_TYPE_REQUIRED'); const raw = await readBody(request); if (!raw.length) throw new ManagementMethodStoreError('INVALID_JSON'); try { return JSON.parse(raw.toString('utf8')) as Record<string, unknown> } catch { throw new ManagementMethodStoreError('INVALID_JSON') } }
function hashInput(value: unknown) { return createHash('sha256').update(JSON.stringify(value)).digest('hex') }
function methodForView(method: any, view: 'draft' | 'readable') { if (view === 'readable') return method.readableSnapshot ? { ...method, workingDraft: undefined, readableSnapshot: method.readableSnapshot } : null; return method }
export function mapManagementMethodError(error: unknown) { const code = error instanceof ManagementMethodStoreError || error instanceof ManagementMethodMediaError || error instanceof ManagementMethodAiError ? error.code : 'MANAGEMENT_METHOD_WRITE_FAILED'; const status = code === 'IDENTITY_CONTEXT_REQUIRED' ? 401 : code === 'IDENTITY_PROVIDER_NOT_CONFIGURED' || code === 'AI_PROVIDER_NOT_CONFIGURED' ? 503 : code === 'METHOD_NOT_FOUND' || code === 'MEDIA_NOT_FOUND' ? 404 : code === 'COMMAND_ID_REUSED' || code === 'CREATION_REQUEST_REUSED' || code.includes('REVISION_CONFLICT') || code === 'SNAPSHOT_REQUIRED' ? 409 : code === 'PAYLOAD_TOO_LARGE' || code === 'MEDIA_TOO_LARGE' ? 413 : code === 'VALIDATION_FAILED' || code === 'AI_OUTPUT_INVALID' || code === 'MEDIA_TYPE_INVALID' || code === 'MEDIA_CONTEXT_REQUIRED' || code === 'OWNER_INVALID' || code === 'CONTENT_TYPE_REQUIRED' || code === 'INVALID_JSON' ? (code === 'CONTENT_TYPE_REQUIRED' || code === 'INVALID_JSON' ? 400 : 422) : code === 'AI_GENERATION_BUSY' ? 429 : code === 'AI_GENERATION_TIMEOUT' ? 504 : code === 'FORBIDDEN' ? 403 : 500; return { status, code } }

async function handle(request: IncomingMessage, response: ServerResponse, root: string, devEnabled: boolean) {
  const url = new URL(request.url ?? '/', 'http://orgmaster.local'); const path = url.pathname.slice(MANAGEMENT_METHOD_API_PATH.length) || '/'; const actor = actorFromRequest(request, devEnabled); if (!actor) throw new ManagementMethodStoreError(devEnabled ? 'IDENTITY_CONTEXT_REQUIRED' : 'IDENTITY_PROVIDER_NOT_CONFIGURED')
  const current = await readManagementMethodStore(root)
  if (path === '/session' && request.method === 'GET') { const capabilities = await capabilitiesFor(root, actor); sendJson(response, 200, { runtimeMode: actor.bootstrap ? 'local-development' : 'verified-session', actor: { principalId: actor.principalId, subjectHint: '••••' }, capabilities, draftGeneration: process.env.OPENAI_API_KEY && process.env.ORGMASTER_MANAGEMENT_METHOD_MODEL ? 'configured' : 'unavailable' }); return }
  if (path === '/' && request.method === 'GET') {
    const view = url.searchParams.get('view') === 'readable' ? 'readable' : 'draft'; const capability = view === 'readable' ? 'readReadable' : 'readDraft'; if (!await capabilityFor(root, actor, capability)) throw new ManagementMethodStoreError('FORBIDDEN')
    const query = (url.searchParams.get('q') ?? '').trim().slice(0, 120).toLocaleLowerCase(); const summaries = current.store.methods.filter((method) => { if (view === 'readable' && !method.readableSnapshot) return false; const haystack = `${method.code} ${method.title}`.toLocaleLowerCase(); return !query || haystack.includes(query) }).map((method) => ({ id: method.id, code: method.code, title: method.title, ownerEmployeeId: method.ownerEmployeeId, status: deriveMethodStatus(method), updatedAt: method.updatedAt, methodRevision: method.methodRevision })); sendJson(response, 200, { summaries, revision: storeRevision(current.raw) }); return
  }
  if (path === '/' && request.method === 'POST') {
    if (!await capabilityFor(root, actor, 'create')) throw new ManagementMethodStoreError('FORBIDDEN')
    const parsed = createInputSchema.safeParse(await jsonBody(request)); if (!parsed.success) throw new ManagementMethodStoreError('VALIDATION_FAILED', '建立資料無效', parsed.error.issues)
    const input = parsed.data as ManagementMethodCreateInputV1; const inputKey = `${input.creationRequestId}:${hashInput(input)}`; const existing = inflight.get(inputKey); if (existing) { const result = await existing as any; sendJson(response, result.replayed ? 200 : 201, { method: result.method }); return }
    const generator = process.env.OPENAI_API_KEY && process.env.ORGMASTER_MANAGEMENT_METHOD_MODEL ? selectManagementMethodDraftGenerator() : (request.headers['x-orgmaster-dev-fake-ai'] === '1' ? selectManagementMethodDraftGenerator() : null); if (!generator) throw new ManagementMethodAiError('AI_PROVIDER_NOT_CONFIGURED')
    const task = generator.generate(input).then((generated) => createManagementMethod(root, input, generated.title, generated.body, generated.meta, actor.principalId)).finally(() => inflight.delete(inputKey)); inflight.set(inputKey, task); const result = await task; sendJson(response, result.replayed ? 200 : 201, { method: result.method }); return
  }
  const methodId = path.startsWith('/') ? decodeURIComponent(path.split('/')[1] ?? '') : ''
  if (methodId && path === `/${encodeURIComponent(methodId)}` && request.method === 'GET') {
    const view = url.searchParams.get('view') === 'readable' ? 'readable' : 'draft'; if (!await capabilityFor(root, actor, view === 'readable' ? 'readReadable' : 'readDraft')) throw new ManagementMethodStoreError('METHOD_NOT_FOUND'); const method = current.store.methods.find((item) => item.id === methodId); if (!method) throw new ManagementMethodStoreError('METHOD_NOT_FOUND'); const projected = methodForView(method, view); if (!projected) throw new ManagementMethodStoreError('METHOD_NOT_FOUND'); sendJson(response, 200, { method: projected, view }, method.methodRevision); return
  }
  if (methodId && path === `/${encodeURIComponent(methodId)}/draft` && request.method === 'PATCH') {
    if (!await capabilityFor(root, actor, 'editDraft')) throw new ManagementMethodStoreError('FORBIDDEN'); const body = await jsonBody(request); const result = await saveDraft(root, methodId, String(body.expectedDraftRevision ?? ''), String(body.commandId ?? ''), body.body as any, actor.principalId); sendJson(response, 200, { method: result.result.method }, result.result.method.methodRevision); return
  }
  if (methodId && path === `/${encodeURIComponent(methodId)}/metadata` && request.method === 'PATCH') {
    if (!await capabilityFor(root, actor, 'manageMetadata')) throw new ManagementMethodStoreError('FORBIDDEN'); const body = await jsonBody(request); const result = await updateMethodMetadata(root, methodId, String(body.expectedMethodRevision ?? ''), String(body.commandId ?? ''), String(body.title ?? ''), body.ownerEmployeeId === null ? null : String(body.ownerEmployeeId ?? ''), actor.principalId); sendJson(response, 200, { method: result.result.method }, result.result.method.methodRevision); return
  }
  if (methodId && path === `/${encodeURIComponent(methodId)}/readable` && request.method === 'POST') {
    if (!await capabilityFor(root, actor, 'manageReadable')) throw new ManagementMethodStoreError('FORBIDDEN'); const body = await jsonBody(request); const result = await provideReadable(root, methodId, String(body.expectedDraftRevision ?? ''), String(body.expectedMethodRevision ?? ''), String(body.commandId ?? ''), actor.principalId); sendJson(response, 200, { method: result.result.method }, result.result.method.methodRevision); return
  }
  if (methodId && path === `/${encodeURIComponent(methodId)}/readable` && request.method === 'DELETE') {
    if (!await capabilityFor(root, actor, 'manageReadable')) throw new ManagementMethodStoreError('FORBIDDEN'); const body = await jsonBody(request); const result = await stopReadable(root, methodId, String(body.expectedMethodRevision ?? ''), String(body.commandId ?? ''), actor.principalId); sendJson(response, 200, { method: result.result.method }, result.result.method.methodRevision); return
  }
  if (methodId && path === `/${encodeURIComponent(methodId)}/restore` && request.method === 'POST') {
    if (!await capabilityFor(root, actor, 'editDraft')) throw new ManagementMethodStoreError('FORBIDDEN'); const body = await jsonBody(request); const result = await restoreDraft(root, methodId, String(body.expectedDraftRevision ?? ''), String(body.expectedMethodRevision ?? ''), String(body.commandId ?? ''), actor.principalId); sendJson(response, 200, { method: result.result.method }, result.result.method.methodRevision); return
  }
  if (path === '/media' && request.method === 'POST') {
    if (!await capabilityFor(root, actor, 'editDraft')) throw new ManagementMethodStoreError('FORBIDDEN'); const methodIdParam = url.searchParams.get('methodId'); if (methodIdParam && !current.store.methods.some((method) => method.id === methodIdParam)) throw new ManagementMethodStoreError('METHOD_NOT_FOUND'); const bytes = await readBody(request, 8 * 1024 * 1024); const mimeType = String(request.headers['content-type'] ?? '').split(';')[0].trim(); const altText = decodeURIComponent(String(request.headers['x-orgmaster-media-alt'] ?? '')); const media = await ingestManagementMethodMedia(root, { bytes, mimeType, altText, methodId: methodIdParam, creationRequestId: url.searchParams.get('creationRequestId'), principalId: actor.principalId }); try { await withStoreMutation(root, async ({ store }) => ({ store: { ...store, mediaAssets: [...store.mediaAssets, media] }, result: media })) } catch (error) { await removeMediaFileIfExists(root, media.storedFileRef); throw error } sendJson(response, 201, { media }); return
  }
  if (path.startsWith('/media/') && request.method === 'GET') {
    const mediaId = decodeURIComponent(path.slice('/media/'.length)); const methodIdParam = url.searchParams.get('methodId') ?? ''; const view = url.searchParams.get('view') === 'readable' ? 'readable' : 'draft'; if (!await capabilityFor(root, actor, view === 'readable' ? 'readReadable' : 'readDraft')) throw new ManagementMethodStoreError('MEDIA_NOT_FOUND'); const media = await readManagementMethodMedia(root, current.store, mediaId, methodIdParam, view); response.statusCode = 200; response.setHeader('Content-Type', media.asset.mimeType); response.setHeader('Cache-Control', 'no-store'); response.setHeader('X-Content-Type-Options', 'nosniff'); response.end(media.bytes); return
  }
  sendJson(response, 404, { error: 'ROUTE_NOT_FOUND' })
}

function middleware(root: string, devEnabled: boolean) { return (request: IncomingMessage, response: ServerResponse, next: Connect.NextFunction) => { if (!request.url?.startsWith(MANAGEMENT_METHOD_API_PATH)) return next(); void handle(request, response, root, devEnabled).catch((error) => { const mapped = mapManagementMethodError(error); sendJson(response, mapped.status, { error: mapped.code, ...(error instanceof ManagementMethodStoreError && error.issues ? { issues: error.issues } : {}) }) }) } }
function mountedMiddleware(root: string, devEnabled: boolean) { return (request: IncomingMessage, response: ServerResponse, next: Connect.NextFunction) => { const original = request.url ?? '/'; request.url = `${MANAGEMENT_METHOD_API_PATH}${original === '/' ? '' : original}`; void handle(request, response, root, devEnabled).catch((error) => { const mapped = mapManagementMethodError(error); sendJson(response, mapped.status, { error: mapped.code, ...(error instanceof ManagementMethodStoreError && error.issues ? { issues: error.issues } : {}) }) }) } }
export function createOrgmasterManagementMethodMiddleware(root = process.cwd(), devEnabled = false): Connect.NextHandleFunction { return middleware(root, devEnabled) }
export function orgmasterManagementMethodApiPlugin(): Plugin { return { name: 'orgmaster-management-method-api', configureServer(server: ViteDevServer) { const devEnabled = server.config.command === 'serve' && server.config.mode === 'development'; server.middlewares.use(middleware(server.config.root, devEnabled)); server.middlewares.use(MANAGEMENT_METHOD_API_PATH, mountedMiddleware(server.config.root, devEnabled)) }, configurePreviewServer(server: PreviewServer) { server.middlewares.use(middleware(process.cwd(), false)); server.middlewares.use(MANAGEMENT_METHOD_API_PATH, mountedMiddleware(process.cwd(), false)) } } }
