import { mkdtemp, readFile, rm, stat } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { createUuidV7 } from '../src/employeeIdentity'
import { AccountEnrollmentStoreError, createAccountEnrollmentStore, getAccountEnrollmentPaths } from './orgmasterAccountEnrollmentStore'

describe('account enrollment local ledger', () => {
  it('pure GET stays empty and first legal mutation lazy seeds', async () => { const root = await mkdtemp(join(tmpdir(), 'orgmaster-account-')); try { const store = createAccountEnrollmentStore({ root, devEnabled: true }); const empty = await store.readExisting(); expect(empty.exists).toBe(false); await expect(stat(getAccountEnrollmentPaths(root).current)).rejects.toThrow(); const id = createUuidV7(); const receipt = { commandId: 'command-1', requestHash: 'a'.repeat(64), action: 'invite_new' as const, employeeId: 'employee-1', enrollmentId: id, providerRequestKey: `account-enrollment:${id}`, createdAt: new Date().toISOString() }; await store.commit(null, (document) => ({ ...document, enrollments: [{ id, employeeId: 'employee-1', kind: 'invite_new', providerKey: 'local-deterministic', providerRequestKey: receipt.providerRequestKey, targetEmail: 'new@orgmaster.test', targetEmailHash: 'b'.repeat(64), targetEmailHint: 'n***w@orgmaster.test', providerOperationRef: null, status: 'requested', statusReasonCode: 'invite_requested', candidateLeaseId: null, identityLinkId: null, createdByPrincipalId: 'p', createdAt: receipt.createdAt, updatedAt: receipt.createdAt, expiresAt: null, revision: 1 }], commands: [receipt] })); const saved = await store.readExisting(); expect(saved.exists).toBe(true); expect(JSON.parse(await readFile(getAccountEnrollmentPaths(root).current, 'utf8')).schemaVersion).toBe(1) } finally { await rm(root, { recursive: true, force: true }) } })
  it('enforces revision CAS and disabled mode never writes', async () => { const root = await mkdtemp(join(tmpdir(), 'orgmaster-account-')); try { const store = createAccountEnrollmentStore({ root, devEnabled: false }); await expect(store.commit(null, (document) => document)).rejects.toMatchObject({ code: 'ACCOUNT_ENROLLMENT_WRITE_FAILED' }); const enabled = createAccountEnrollmentStore({ root, devEnabled: true }); await expect(enabled.commit('wrong', (document) => document)).rejects.toBeInstanceOf(AccountEnrollmentStoreError) } finally { await rm(root, { recursive: true, force: true }) } })
})
