import { createHash, randomUUID } from 'node:crypto'
import { mkdir, readFile, rename, stat, unlink, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { getWorkspaceIndex, getWorkspaceVersion } from './orgmasterWorkspaceStore'
import { readStoredDocument } from './orgmasterApi'
import { applyGovernanceCommand, canonicalJson, commandHash, sha256 } from '../src/governance/commands'
import { ALL_SEED_PERMISSIONS, GOVERNANCE_APPLICATIONS, GOVERNANCE_ROLE_TEMPLATES, ORGMASTER_PERMISSIONS } from '../src/governance/aiPdmCatalog'
import { assertValidDocument, buildOrganizationSnapshot, GovernanceValidationError, validateDocument, validatePolicyData } from '../src/governance/validation'
import type { GovernanceActorContext, GovernanceAuditEventV1, GovernanceCommand, GovernanceDocumentV1, GovernanceOrgSource, GovernancePolicyDataV1, GovernancePolicyVersionV1 } from '../src/governance/types'

export class GovernanceStoreError extends Error { constructor(public readonly code: string, public readonly details?: unknown) { super(code); this.name = 'GovernanceStoreError' } }
export function getGovernancePaths(rootDirectory = process.cwd()) { const data = resolve(rootDirectory, 'data'); return { current: resolve(data, 'orgmaster-governance.v1.json'), previous: resolve(data, 'orgmaster-governance.v1.previous.json') } }
export function documentRevision(raw: string) { return sha256(raw) }
const locks = new Map<string, Promise<void>>()
async function withLock<T>(root: string, fn: () => Promise<T>) { const key = resolve(root); const previous = locks.get(key) ?? Promise.resolve(); let release!: () => void; const current = new Promise<void>((r) => { release = r }); const queued = previous.then(() => current); locks.set(key, queued); await previous; try { return await fn() } finally { release(); if (locks.get(key) === queued) locks.delete(key) } }
async function exists(path: string) { try { await stat(path); return true } catch { return false } }
async function writeAtomic(path: string, raw: string) { await mkdir(dirname(path), { recursive: true }); const temp = `${path}.${process.pid}.${randomUUID()}.tmp`; try { await writeFile(temp, raw, 'utf8'); if (await readFile(temp, 'utf8') !== raw) throw new GovernanceStoreError('GOVERNANCE_WRITE_FAILED'); await rename(temp, path) } catch (error) { try { await unlink(temp) } catch { /* exact temp best effort */ } throw error } }
function emptyData(): GovernancePolicyDataV1 { return { applications: GOVERNANCE_APPLICATIONS.map((v) => ({ ...v })), identityLinks: [], applicationRoles: GOVERNANCE_ROLE_TEMPLATES.map((v) => ({ ...v })), permissions: ALL_SEED_PERMISSIONS.map((v) => ({ ...v })), rolePermissionGrants: ORGMASTER_PERMISSIONS.map((permission) => ({ id: `grant-orgmaster-admin-${permission.id}`, roleId: 'role-orgmaster-admin', permissionId: permission.id, effect: 'allow' as const })), roleAssignments: [], delegations: [], approvalPolicies: [] } }
export function createSeedDocument(now = new Date().toISOString()): GovernanceDocumentV1 { return { app: 'OrgMaster', schemaVersion: 1, draft: { ...emptyData(), basePolicyVersionId: null, updatedAt: now }, activePolicyVersionId: null, publishedVersions: [], auditEvents: [] } }
function eventHash(event: Omit<GovernanceAuditEventV1, 'eventHash'>) { return sha256(canonicalJson(event)) }
function appendAudit(document: GovernanceDocumentV1, command: { commandId: string; reason: string }, actor: GovernanceActorContext, info: { action: string; entityType: string; entityId: string | null; beforeHash: string | null; afterHash: string | null }, now = new Date().toISOString()) {
  const previousEventHash = document.auditEvents.at(-1)?.eventHash ?? null; const base = { id: `audit-${randomUUID()}`, commandId: command.commandId, commandHash: commandHash(command as GovernanceCommand), occurredAt: now, actorPrincipalId: actor.principalId, action: info.action, entityType: info.entityType, entityId: info.entityId, reason: command.reason, beforeHash: info.beforeHash, afterHash: info.afterHash, previousEventHash }; const event = { ...base, eventHash: eventHash(base) }; return { ...document, auditEvents: [...document.auditEvents, event] }
}
function validateAuditChain(document: GovernanceDocumentV1) { let previous: string | null = null; for (const event of document.auditEvents) { const { eventHash: actual, ...base } = event; if (event.previousEventHash !== previous || eventHash(base) !== actual) throw new GovernanceStoreError('AUDIT_CHAIN_INVALID'); previous = actual } }
function actorHasDraftPermission(document: GovernanceDocumentV1, actor: GovernanceActorContext, permissionCode: string, now = new Date().toISOString()) {
  const link = document.draft.identityLinks.find((value) => value.principalId === actor.principalId && value.issuer === actor.issuer && value.subject === actor.subject && value.status === 'active' && Date.parse(value.validFrom) <= Date.parse(now) && (!value.validTo || Date.parse(now) < Date.parse(value.validTo)))
  if (!link) return false
  const permission = document.draft.permissions.find((value) => value.applicationId === 'orgmaster' && value.code === permissionCode && value.status === 'active')
  if (!permission) return false
  const roleIds = new Set(document.draft.roleAssignments.filter((value) => value.employeeId === link.employeeId && value.status === 'active' && value.scope.kind === 'global' && Date.parse(value.validFrom) <= Date.parse(now) && (!value.validTo || Date.parse(now) < Date.parse(value.validTo))).map((value) => value.roleId))
  return document.draft.rolePermissionGrants.some((grant) => roleIds.has(grant.roleId) && grant.permissionId === permission.id && grant.effect === 'allow')
}
async function readRaw(root: string) { const path = getGovernancePaths(root).current; try { const raw = await readFile(path, 'utf8'); const document = JSON.parse(raw) as GovernanceDocumentV1; if (document.schemaVersion !== 1) throw new GovernanceStoreError('GOVERNANCE_SCHEMA_UNSUPPORTED'); validateAuditChain(document); if (validateDocument(document).length) throw new GovernanceStoreError('GOVERNANCE_READ_FAILED'); return { raw, document, revision: documentRevision(raw) } } catch (error) { if (error instanceof GovernanceStoreError) throw error; throw new GovernanceStoreError('GOVERNANCE_READ_FAILED') } }
function syncOrgMasterManagementMethodCatalog(document: GovernanceDocumentV1) {
  const missing = ORGMASTER_PERMISSIONS.filter((permission) => !document.draft.permissions.some((existing) => existing.applicationId === permission.applicationId && existing.code === permission.code))
  if (!missing.length) return document
  const draft = { ...document.draft, permissions: [...document.draft.permissions, ...missing.map((permission) => ({ ...permission }))], rolePermissionGrants: [...document.draft.rolePermissionGrants, ...missing.map((permission) => ({ id: `grant-orgmaster-admin-${permission.id}`, roleId: 'role-orgmaster-admin', permissionId: permission.id, effect: 'allow' as const }))], updatedAt: new Date().toISOString() }
  const actor: GovernanceActorContext = { principalId: 'system', issuer: 'system', subject: 'system', employeeId: null, bootstrap: true }
  return appendAudit({ ...document, draft }, { commandId: `system-catalog-sync-${sha256(missing.map((permission) => permission.code).join('|')).slice(0, 16)}`, reason: 'DEV-032 管理辦法 permission catalog 相容同步' }, actor, { action: 'ORGMASTER_SYSTEM_CATALOG_SYNCED', entityType: 'permissionCatalog', entityId: 'orgmaster.management-methods', beforeHash: sha256(canonicalJson(document.draft)), afterHash: sha256(canonicalJson(draft)) })
}
export async function ensureGovernanceStore(root = process.cwd()) { return withLock(root, async () => { const paths = getGovernancePaths(root); if (await exists(paths.current)) { const current = await readRaw(root); const synced = syncOrgMasterManagementMethodCatalog(current.document); if (synced === current.document) return current; await writeAtomic(paths.previous, current.raw); const raw = `${JSON.stringify(synced, null, 2)}\n`; validateAuditChain(synced); await writeAtomic(paths.current, raw); return readRaw(root) } const seed = createSeedDocument(); const eventBase = { commandId: 'system-init', reason: '建立本機治理 V1 store', type: 'GOVERNANCE_INITIALIZED' }; const actor: GovernanceActorContext = { principalId: 'system', issuer: 'system', subject: 'system', employeeId: null, bootstrap: true }; const audited = appendAudit(seed, eventBase, actor, { action: 'GOVERNANCE_INITIALIZED', entityType: 'governance', entityId: null, beforeHash: null, afterHash: sha256(canonicalJson(seed.draft)) }); const raw = `${JSON.stringify(audited, null, 2)}\n`; validateAuditChain(audited); await writeAtomic(paths.current, raw); return { raw, document: audited, revision: documentRevision(raw) } }) }
export async function readGovernanceStore(root = process.cwd()) { return ensureGovernanceStore(root) }
export async function loadOrganizationSource(root = process.cwd()): Promise<GovernanceOrgSource> { try { const index = await getWorkspaceIndex(root); const current = await getWorkspaceVersion(root, index.currentVersionId); return { workspaceVersionId: index.currentVersionId, workspaceRevision: current.version.revision, state: current.document.state } } catch { const legacy = await readStoredDocument(root); return { workspaceVersionId: 'legacy-current', workspaceRevision: legacy.revision, state: legacy.document.state } } }
export async function applyDraftCommand(root: string, expectedRevision: string, command: GovernanceCommand, actor: GovernanceActorContext) { return withLock(root, async () => { const current = await readRaw(root); if (current.revision !== expectedRevision) throw new GovernanceStoreError('REVISION_CONFLICT'); const existing = current.document.auditEvents.find((event) => event.commandId === command.commandId); const hash = commandHash(command); if (existing) { if (existing.commandHash !== hash) throw new GovernanceStoreError('COMMAND_ID_REUSED'); return { status: 'replayed' as const, document: current.document, revision: current.revision } } const applied = applyGovernanceCommand(current.document, command); if (applied.status === 'noop') return { status: 'noop' as const, document: current.document, revision: current.revision }; const source = await loadOrganizationSource(root); const candidate = applied.document; const issues = validateDocument(candidate, source); if (issues.length) throw new GovernanceValidationError(issues); const audited = appendAudit(candidate, command, actor, { action: command.type, entityType: applied.entityType, entityId: applied.entityId, beforeHash: applied.beforeHash, afterHash: applied.afterHash }); return persist(root, current, audited, 'draft') }) }
export async function publishGovernance(root: string, expectedRevision: string, commandId: string, reason: string, organizationVersionId: string, actor: GovernanceActorContext) { return withLock(root, async () => { const current = await readRaw(root); if (current.revision !== expectedRevision) throw new GovernanceStoreError('REVISION_CONFLICT'); const source = await loadOrganizationSource(root); if (source.workspaceVersionId !== organizationVersionId) throw new GovernanceStoreError('ORGANIZATION_VERSION_INVALID'); if (!source.state.employees.some((employee) => current.document.draft.identityLinks.some((link) => link.employeeId === employee.id && link.principalId === actor.principalId && link.status === 'active'))) throw new GovernanceStoreError('PUBLISHER_NOT_LINKED'); if (!actorHasDraftPermission(current.document, actor, 'orgmaster.governance.publish')) throw new GovernanceStoreError('GOVERNANCE_PUBLISH_REQUIRED'); const issues = validatePolicyData(current.document.draft, source); if (issues.length) throw new GovernanceValidationError(issues); const publishCommand = { commandId, reason, type: 'PUBLISH_POLICY' }; const existing = current.document.auditEvents.find((event) => event.commandId === commandId); if (existing) { if (existing.commandHash !== commandHash(publishCommand as GovernanceCommand)) throw new GovernanceStoreError('COMMAND_ID_REUSED'); return { status: 'replayed' as const, document: current.document, revision: current.revision } } const snapshot = buildOrganizationSnapshot(source); const policy = { ...current.document.draft, basePolicyVersionId: current.document.draft.basePolicyVersionId } as GovernancePolicyDataV1; const version: GovernancePolicyVersionV1 = { id: `policy-${randomUUID()}`, versionNumber: current.document.publishedVersions.length + 1, publishedAt: new Date().toISOString(), publishedByPrincipalId: actor.principalId, publishReason: reason, snapshotHash: sha256(canonicalJson({ policy, snapshot })), policy, organizationSnapshot: snapshot }; let next: GovernanceDocumentV1 = { ...current.document, activePolicyVersionId: version.id, publishedVersions: [...current.document.publishedVersions, version], draft: { ...current.document.draft, basePolicyVersionId: version.id } }; next = appendAudit(next, publishCommand, actor, { action: 'PUBLISH_POLICY', entityType: 'policyVersion', entityId: version.id, beforeHash: null, afterHash: version.snapshotHash }); return persist(root, current, next, 'publish') }) }
export async function setActivePolicy(root: string, expectedRevision: string, commandId: string, reason: string, versionId: string | null, actor: GovernanceActorContext) { return withLock(root, async () => { const current = await readRaw(root); if (current.revision !== expectedRevision) throw new GovernanceStoreError('REVISION_CONFLICT'); if (versionId && !current.document.publishedVersions.some((v) => v.id === versionId)) throw new GovernanceStoreError('POLICY_VERSION_NOT_FOUND'); if (!actorHasDraftPermission(current.document, actor, 'orgmaster.governance.publish') && !(!current.document.activePolicyVersionId && actor.bootstrap)) throw new GovernanceStoreError('GOVERNANCE_PUBLISH_REQUIRED'); const command = { commandId, reason, type: versionId ? 'REACTIVATE_POLICY' : 'REVOKE_POLICY' }; const existing = current.document.auditEvents.find((event) => event.commandId === commandId); if (existing) { if (existing.commandHash !== commandHash(command as GovernanceCommand)) throw new GovernanceStoreError('COMMAND_ID_REUSED'); return { status: 'replayed' as const, document: current.document, revision: current.revision } } const audited = appendAudit({ ...current.document, activePolicyVersionId: versionId }, command, actor, { action: command.type, entityType: 'policyVersion', entityId: versionId, beforeHash: current.document.activePolicyVersionId, afterHash: versionId }); return persist(root, current, audited, 'active') }) }
async function persist(root: string, current: { raw: string; document: GovernanceDocumentV1; revision: string }, document: GovernanceDocumentV1, _kind: string) { assertValidDocument(document); const paths = getGovernancePaths(root); await writeAtomic(paths.previous, current.raw); const raw = `${JSON.stringify(document, null, 2)}\n`; await writeAtomic(paths.current, raw); const reread = await readRaw(root); return { status: 'applied' as const, document: reread.document, revision: reread.revision } }
export async function readGovernanceAudit(root = process.cwd(), limit = 50, cursor = 0) { const current = await readRaw(root); const items = [...current.document.auditEvents].reverse(); const start = Math.max(0, Number(cursor) || 0); const page = items.slice(start, start + Math.max(1, Math.min(100, limit))); return { items: page, nextCursor: start + page.length < items.length ? String(start + page.length) : null, revision: current.revision } }
