import { cp, mkdir, mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { createAccountEnrollmentService } from './orgmasterAccountEnrollmentService'
import { createLocalAccountProvisioningAdapter } from './orgmasterAccountProvisioningPort'
import { DEVELOPMENT_AUTH_PROFILES } from './orgmasterGovernanceIdentity'

describe('account enrollment service safeguards', () => {
  it('production mode fails closed and recovery does not probe a local ledger', async () => { const root = await mkdtemp(join(tmpdir(), 'orgmaster-service-')); try { const service = createAccountEnrollmentService({ root, devEnabled: false, provider: null }); await expect(service.recoverIncompleteEnrollments()).resolves.toEqual({ inspected: 0, advanced: 0, remaining: 0 }); await expect(service.invite({ principalId: 'p', issuer: 'i', subject: 's', employeeId: null, bootstrap: false }, { commandId: 'c', employeeId: 'missing', email: 'x@orgmaster.test' })).rejects.toBeDefined() } finally { await rm(root, { recursive: true, force: true }) } })
  it('projects an employee and records an idempotent local invitation', async () => { const root = await mkdtemp(join(tmpdir(), 'orgmaster-service-')); try { await mkdir(join(root, 'data', 'orgmaster-versions'), { recursive: true }); await cp(join(process.cwd(), 'data', 'orgmaster-governance.v3.json'), join(root, 'data', 'orgmaster-governance.v3.json')); await cp(join(process.cwd(), 'data', 'orgmaster-workspace.v1.json'), join(root, 'data', 'orgmaster-workspace.v1.json')); await cp(join(process.cwd(), 'data', 'orgmaster-versions', 'current-c9ad8769d8d1d4319e29.json'), join(root, 'data', 'orgmaster-versions', 'current-c9ad8769d8d1d4319e29.json')); const actor = { principalId: DEVELOPMENT_AUTH_PROFILES[0].principalId, issuer: 'urn:orgmaster:dev', subject: DEVELOPMENT_AUTH_PROFILES[0].subject, employeeId: DEVELOPMENT_AUTH_PROFILES[0].employeeId, bootstrap: true }; const service = createAccountEnrollmentService({ root, devEnabled: true, provider: createLocalAccountProvisioningAdapter() }); const employeeId = '14466657-006e-4538-aade-5877c166b038'; const initial = await service.readEmployeeAccess(actor, employeeId); expect(initial.capabilities.invite).toBe(true); const result = await service.invite(actor, { commandId: 'invite-command-1', employeeId, email: 'new.service@orgmaster.test' }); expect(result.disposition).toBe('created'); expect(result.view.enrollments[0]).toMatchObject({ status: 'pending_acceptance', emailHint: 'n******e@orgmaster.test' }); await expect(service.invite(actor, { commandId: 'invite-command-1', employeeId, email: 'new.service@orgmaster.test' })).resolves.toMatchObject({ disposition: 'replayed' }) } finally { await rm(root, { recursive: true, force: true }) } })
})
