import type { IncomingMessage, ServerResponse } from 'node:http'
import type { Connect, Plugin, PreviewServer, ViteDevServer } from 'vite'
import { applyDraftCommand, publishGovernance, readGovernanceAudit, readGovernanceStore, setActivePolicy, validateAssignmentCandidate, GovernanceStoreError } from './orgmasterGovernanceStore'
import { DEV_PRINCIPAL_ID, resolveDevelopmentIdentity } from './orgmasterGovernanceIdentity'
import { evaluatePermission } from '../src/governance/evaluatePermission'
import { GovernanceValidationError } from '../src/governance/validation'
import { ensureCommandShape } from '../src/governance/commands'
import type { GovernanceActorContext, GovernanceCommandV2 } from '../src/governance/types'
import { createHash } from 'node:crypto'
import { readAiPdmRoleCatalog } from '../src/governance/aiPdmCatalog'

export const API_PATH = '/api/orgmaster/governance'
const MAX_BODY = 1024 * 1024
const V2_COMMANDS = ['UPSERT_IDENTITY_LINK', 'SET_IDENTITY_LINK_STATUS', 'UPSERT_APPLICATION_ROLE', 'SET_APPLICATION_ROLE_STATUS', 'UPSERT_PERMISSION', 'SET_PERMISSION_STATUS', 'SET_ROLE_PERMISSION_GRANT', 'REMOVE_ROLE_PERMISSION_GRANT', 'UPSERT_ROLE_ASSIGNMENT', 'REVOKE_ROLE_ASSIGNMENT', 'UPSERT_ROLE_DELEGATION', 'REVOKE_ROLE_DELEGATION'] as const
const LEGACY_EXTERNAL_COMMANDS = ['UPSERT_DELEGATION', 'REVOKE_DELEGATION', 'UPSERT_APPROVAL_POLICY', 'SET_APPROVAL_POLICY_STATUS']
function sendJson(response: ServerResponse, status: number, payload: unknown, revision?: string) { response.statusCode = status; response.setHeader('Content-Type', 'application/json; charset=utf-8'); response.setHeader('Cache-Control', 'no-store'); if (revision) response.setHeader('X-OrgMaster-Governance-Revision', revision); response.end(JSON.stringify(payload)) }
function readBody(request: IncomingMessage) { return new Promise<string>((resolve, reject) => { const chunks: Buffer[] = []; let size = 0; request.on('data', (chunk: Buffer | string) => { const buffer = Buffer.from(chunk); size += buffer.length; if (size > MAX_BODY) { reject(new GovernanceStoreError('PAYLOAD_TOO_LARGE')); request.destroy(); return } chunks.push(buffer) }); request.on('end', () => resolve(Buffer.concat(chunks).toString('utf8'))); request.on('error', reject) }) }
async function parseBody(request: IncomingMessage) { const contentType = String(request.headers['content-type'] ?? '').toLowerCase(); if (!contentType.startsWith('application/json')) throw new GovernanceStoreError('INVALID_JSON'); const raw = await readBody(request); if (!raw) throw new GovernanceStoreError('INVALID_JSON'); try { return JSON.parse(raw) as Record<string, unknown> } catch { throw new GovernanceStoreError('INVALID_JSON') } }
function sanitizeIdentity(link: any) { const { subject: _subject, ...rest } = link; return { ...rest, subjectHint: typeof link.subject === 'string' && link.subject.length > 4 ? `••••${link.subject.slice(-4)}` : '••••', subjectFingerprint: createHash('sha256').update(`${link.issuer}\0${link.subject}`).digest('hex').slice(0, 12) } }
function sanitizedDocument(document: any) { return { ...document, draft: { ...document.draft, identityLinks: document.draft.identityLinks.map(sanitizeIdentity) }, publishedVersions: document.publishedVersions.map((version: any) => ({ ...version, policy: { ...version.policy, identityLinks: version.policy.identityLinks.map(sanitizeIdentity) } })) } }
export function governanceErrorStatus(code: string) { if (code === 'IDENTITY_CONTEXT_REQUIRED') return 401; if (code === 'IDENTITY_PROVIDER_NOT_CONFIGURED' || code === 'EXTERNAL_CATALOG_UNAVAILABLE') return 503; if (code === 'GOVERNANCE_ADMIN_REQUIRED' || code === 'GOVERNANCE_PUBLISH_REQUIRED') return 403; if (code === 'POLICY_VERSION_NOT_FOUND') return 404; if (code === 'PAYLOAD_TOO_LARGE') return 413; if (['REVISION_CONFLICT', 'COMMAND_ID_REUSED', 'ORGANIZATION_VERSION_INVALID', 'EXTERNAL_CATALOG_READ_ONLY', 'EXTERNAL_CATALOG_VERSION_CONFLICT', 'EXTERNAL_CATALOG_STALE', 'LEGACY_MIGRATION_UNRESOLVED', 'LEGACY_POLICY_REACTIVATION_FORBIDDEN'].includes(code)) return 409; if (['GOVERNANCE_VALIDATION_FAILED', 'EXTERNAL_CATALOG_INVALID', 'EXTERNAL_ROLE_UNKNOWN', 'EXTERNAL_ROLE_INACTIVE', 'EXTERNAL_ROLE_UNASSIGNABLE', 'EXTERNAL_SCOPE_UNSUPPORTED', 'ROLE_DELEGATION_INVALID', 'PUBLISHER_NOT_LINKED', 'GOVERNANCE_ADMIN_CONTINUITY_REQUIRED'].includes(code)) return 422; if (code === 'INVALID_JSON') return 400; if (code === 'LEGACY_GOVERNANCE_EVALUATOR_RETIRED') return 410; return 500 }
function errorResponse(response: ServerResponse, error: unknown) { const code = error instanceof GovernanceStoreError ? error.code : error instanceof GovernanceValidationError ? 'GOVERNANCE_VALIDATION_FAILED' : 'GOVERNANCE_READ_FAILED'; sendJson(response, governanceErrorStatus(code), { error: code, ...(error instanceof GovernanceValidationError ? { issues: error.issues } : {}) }) }
function actorOrThrow(request: IncomingMessage, enabled: boolean) { const actor = resolveDevelopmentIdentity(request, enabled); if (!actor) throw new GovernanceStoreError(enabled ? 'IDENTITY_CONTEXT_REQUIRED' : 'IDENTITY_PROVIDER_NOT_CONFIGURED'); return actor }
function canManage(document: any, actor: GovernanceActorContext) { if (actor.bootstrap && !document.activePolicyVersionId) return true; return evaluatePermission(document, { applicationId: 'orgmaster', issuer: actor.issuer, subject: actor.subject, permissionCode: 'orgmaster.governance.manage', scope: { kind: 'global' } }).status === 'allowed' }
function canPermission(document: any, actor: GovernanceActorContext, permissionCode: string) { if (actor.bootstrap && !document.activePolicyVersionId) return true; return evaluatePermission(document, { applicationId: 'orgmaster', issuer: actor.issuer, subject: actor.subject, permissionCode, scope: { kind: 'global' } }).status === 'allowed' }
async function handle(request: IncomingMessage, response: ServerResponse, root: string, devEnabled: boolean) {
  const url = new URL(request.url ?? '/', 'http://orgmaster.local'); const path = url.pathname.slice(API_PATH.length) || '/'; const actor = actorOrThrow(request, devEnabled); const current = await readGovernanceStore(root); const document = current.document
  if (path === '/session' && request.method === 'GET') { sendJson(response, 200, { runtimeMode: devEnabled ? 'local-development' : 'unavailable', actor: { principalId: DEV_PRINCIPAL_ID, subjectHint: '••••' }, capabilities: { manage: canManage(document, actor), publish: canPermission(document, actor, 'orgmaster.governance.publish'), simulate: canPermission(document, actor, 'orgmaster.governance.simulate') } }, current.revision); return }
  if (path === '/' && request.method === 'GET') { sendJson(response, 200, { document: sanitizedDocument(document), catalogs: [readAiPdmRoleCatalog()], revision: current.revision, activeVersionId: document.activePolicyVersionId, versions: document.publishedVersions.map((version: any) => ({ id: version.id, kind: version.kind ?? 'legacy-policy-v1', versionNumber: version.versionNumber, publishedAt: version.publishedAt, publishedByPrincipalId: version.publishedByPrincipalId, publishReason: version.publishReason, snapshotHash: version.snapshotHash, organizationVersionId: version.organizationSnapshot.workspaceVersionId, effectState: version.effectState ?? 'legacy' })) }, current.revision); return }
  if (path.startsWith('/versions/') && request.method === 'GET') { const id = decodeURIComponent(path.slice('/versions/'.length)); const version = document.publishedVersions.find((entry: any) => entry.id === id); if (!version) throw new GovernanceStoreError('POLICY_VERSION_NOT_FOUND'); sendJson(response, 200, { version: sanitizedDocument({ ...document, draft: document.draft, publishedVersions: [version] }).publishedVersions[0] }, current.revision); return }
  if (path === '/audit' && request.method === 'GET') { const audit = await readGovernanceAudit(root, Number(url.searchParams.get('limit') ?? 50), Number(url.searchParams.get('cursor') ?? 0)); sendJson(response, 200, audit, current.revision); return }
  if (path === '/draft' && request.method === 'PATCH') { const body = await parseBody(request); if (!canManage(document, actor)) throw new GovernanceStoreError('GOVERNANCE_ADMIN_REQUIRED'); const expected = String(body.expectedRevision ?? request.headers['x-orgmaster-governance-revision'] ?? ''); if (expected !== current.revision) throw new GovernanceStoreError('REVISION_CONFLICT'); const candidate = body.command as any; if (!ensureCommandShape(candidate)) throw new GovernanceStoreError('INVALID_JSON'); if (LEGACY_EXTERNAL_COMMANDS.includes(String(candidate.type))) throw new GovernanceStoreError('EXTERNAL_CATALOG_READ_ONLY'); if (!(V2_COMMANDS as readonly string[]).includes(String(candidate.type))) throw new GovernanceStoreError('INVALID_JSON'); const result = await applyDraftCommand(root, current.revision, candidate as GovernanceCommandV2, actor); sendJson(response, 200, { status: result.status, document: sanitizedDocument(result.document), revision: result.revision }, result.revision); return }
  if (path === '/validate/assignment' && request.method === 'POST') { const body = await parseBody(request); if (!canPermission(document, actor, 'orgmaster.governance.simulate')) throw new GovernanceStoreError('GOVERNANCE_ADMIN_REQUIRED'); const result = await validateAssignmentCandidate(root, body as any); sendJson(response, 200, result, current.revision); return }
  if (path === '/versions' && request.method === 'POST') { const body = await parseBody(request); if (!canManage(document, actor)) throw new GovernanceStoreError('GOVERNANCE_ADMIN_REQUIRED'); const expected = String(body.expectedRevision ?? request.headers['x-orgmaster-governance-revision'] ?? ''); if (expected !== current.revision) throw new GovernanceStoreError('REVISION_CONFLICT'); const result = await publishGovernance(root, current.revision, String(body.commandId ?? ''), String(body.reason ?? ''), String(body.organizationVersionId ?? ''), actor); const version: any = result.document.publishedVersions.at(-1); sendJson(response, 201, { versionSummary: { id: version.id, kind: version.kind, versionNumber: version.versionNumber, publishedAt: version.publishedAt, snapshotHash: version.snapshotHash, organizationVersionId: version.organizationSnapshot.workspaceVersionId, effectState: version.effectState }, revision: result.revision }, result.revision); return }
  if (path === '/active-version' && request.method === 'POST') { const body = await parseBody(request); if (!canManage(document, actor)) throw new GovernanceStoreError('GOVERNANCE_ADMIN_REQUIRED'); const expected = String(body.expectedRevision ?? request.headers['x-orgmaster-governance-revision'] ?? ''); if (expected !== current.revision) throw new GovernanceStoreError('REVISION_CONFLICT'); const result = await setActivePolicy(root, current.revision, String(body.commandId ?? ''), String(body.reason ?? ''), body.versionId === null ? null : String(body.versionId ?? ''), actor); sendJson(response, 200, { activePolicyVersionId: result.document.activePolicyVersionId, revision: result.revision }, result.revision); return }
  if ((path === '/evaluate/permission' || path === '/evaluate/reviewers') && request.method === 'POST') { sendJson(response, 410, { error: 'LEGACY_GOVERNANCE_EVALUATOR_RETIRED' }); return }
  sendJson(response, 404, { error: 'ROUTE_NOT_FOUND' })
}
function middleware(root: string, devEnabled: boolean) { return (request: IncomingMessage, response: ServerResponse, next: Connect.NextFunction) => { if (!request.url?.startsWith(API_PATH)) return next(); void handle(request, response, root, devEnabled).catch((error) => errorResponse(response, error)) } }
export function orgmasterGovernanceApiPlugin(): Plugin { return { name: 'orgmaster-local-governance-api', configureServer(server: ViteDevServer) { server.middlewares.use(middleware(server.config.root, server.config.command === 'serve' && server.config.mode === 'development')) }, configurePreviewServer(server: PreviewServer) { server.middlewares.use(middleware(process.cwd(), false)) } } }
