import type { IncomingMessage, ServerResponse } from 'node:http'
import type { Connect, Plugin, PreviewServer, ViteDevServer } from 'vite'
import { applyDraftCommand, ensureGovernanceStore, getGovernancePaths, loadOrganizationSource, publishGovernance, readGovernanceAudit, readGovernanceStore, setActivePolicy, GovernanceStoreError } from './orgmasterGovernanceStore'
import { DEV_ISSUER, DEV_PRINCIPAL_ID, DEV_SUBJECT, resolveDevelopmentIdentity } from './orgmasterGovernanceIdentity'
import { evaluatePermission } from '../src/governance/evaluatePermission'
import { resolveReviewers } from '../src/governance/resolveReviewers'
import { GovernanceValidationError } from '../src/governance/validation'
import { canonicalJson, commandHash, ensureCommandShape } from '../src/governance/commands'
import type { GovernanceActorContext, GovernanceCommand } from '../src/governance/types'
import { createHash } from 'node:crypto'

const API_PATH = '/api/orgmaster/governance'
const MAX_BODY = 1024 * 1024
function sendJson(response: ServerResponse, status: number, payload: unknown, revision?: string) { response.statusCode = status; response.setHeader('Content-Type', 'application/json; charset=utf-8'); response.setHeader('Cache-Control', 'no-store'); if (revision) response.setHeader('X-OrgMaster-Governance-Revision', revision); response.end(JSON.stringify(payload)) }
function readBody(request: IncomingMessage) { return new Promise<string>((resolve, reject) => { const chunks: Buffer[] = []; let size = 0; request.on('data', (chunk: Buffer | string) => { const buffer = Buffer.from(chunk); size += buffer.length; if (size > MAX_BODY) { reject(new GovernanceStoreError('PAYLOAD_TOO_LARGE')); request.destroy(); return } chunks.push(buffer) }); request.on('end', () => resolve(Buffer.concat(chunks).toString('utf8'))); request.on('error', reject) }) }
async function parseBody(request: IncomingMessage) { const contentType = String(request.headers['content-type'] ?? '').toLowerCase(); if (!contentType.startsWith('application/json')) throw new GovernanceStoreError('INVALID_JSON'); const raw = await readBody(request); if (!raw) throw new GovernanceStoreError('INVALID_JSON'); try { return JSON.parse(raw) as Record<string, unknown> } catch { throw new GovernanceStoreError('INVALID_JSON') } }
function sanitizedDocument(document: any) { return { ...document, draft: { ...document.draft, identityLinks: document.draft.identityLinks.map((link: any) => ({ ...link, subject: undefined, subjectHint: link.subject.length > 4 ? `••••${link.subject.slice(-4)}` : '••••', subjectFingerprint: createHash('sha256').update(`${link.issuer}\0${link.subject}`).digest('hex').slice(0, 12) })) }, publishedVersions: document.publishedVersions.map((version: any) => ({ ...version, policy: { ...version.policy, identityLinks: version.policy.identityLinks.map((link: any) => ({ ...link, subject: undefined, subjectHint: link.subject.length > 4 ? `••••${link.subject.slice(-4)}` : '••••', subjectFingerprint: createHash('sha256').update(`${link.issuer}\0${link.subject}`).digest('hex').slice(0, 12) })) } })) } }
function errorResponse(response: ServerResponse, error: unknown) { const code = error instanceof GovernanceStoreError ? error.code : error instanceof GovernanceValidationError ? 'GOVERNANCE_VALIDATION_FAILED' : 'GOVERNANCE_READ_FAILED'; const status = code === 'IDENTITY_CONTEXT_REQUIRED' ? 401 : code === 'IDENTITY_PROVIDER_NOT_CONFIGURED' ? 503 : code === 'GOVERNANCE_ADMIN_REQUIRED' || code === 'GOVERNANCE_PUBLISH_REQUIRED' ? 403 : code === 'POLICY_VERSION_NOT_FOUND' ? 404 : code === 'REVISION_CONFLICT' || code === 'COMMAND_ID_REUSED' ? 409 : code === 'PAYLOAD_TOO_LARGE' ? 413 : code === 'GOVERNANCE_VALIDATION_FAILED' || code === 'INVALID_JSON' ? (code === 'GOVERNANCE_VALIDATION_FAILED' ? 422 : 400) : 500; sendJson(response, status, { error: code, ...(error instanceof GovernanceValidationError ? { issues: error.issues } : {}) }) }
function revisionMatches(request: IncomingMessage, body: Record<string, unknown>, revision: string) { const expected = String(body.expectedRevision ?? request.headers['x-orgmaster-governance-revision'] ?? ''); return expected === revision }
function actorOrThrow(request: IncomingMessage, enabled: boolean) { const actor = resolveDevelopmentIdentity(request, enabled); if (!actor) throw new GovernanceStoreError(enabled ? 'IDENTITY_CONTEXT_REQUIRED' : 'IDENTITY_PROVIDER_NOT_CONFIGURED'); return actor }
async function canManage(root: string, actor: GovernanceActorContext, document: any) { if (actor.bootstrap && !document.activePolicyVersionId) return true; const evaluation = evaluatePermission(document, { applicationId: 'orgmaster', issuer: actor.issuer, subject: actor.subject, permissionCode: 'orgmaster.governance.manage', scope: { kind: 'global' } }); return evaluation.status === 'allowed' }
function canPermission(document: any, actor: GovernanceActorContext, permissionCode: string) { if (actor.bootstrap && !document.activePolicyVersionId) return true; return evaluatePermission(document, { applicationId: 'orgmaster', issuer: actor.issuer, subject: actor.subject, permissionCode, scope: { kind: 'global' } }).status === 'allowed' }
async function handle(request: IncomingMessage, response: ServerResponse, root: string, devEnabled: boolean) {
  const url = new URL(request.url ?? '/', 'http://orgmaster.local'); const path = url.pathname.slice(API_PATH.length) || '/'; const actor = actorOrThrow(request, devEnabled); const current = await readGovernanceStore(root); const document = current.document
  if (path === '/session' && request.method === 'GET') { sendJson(response, 200, { runtimeMode: devEnabled ? 'local-development' : 'unavailable', actor: { principalId: DEV_PRINCIPAL_ID, subjectHint: '••••' }, capabilities: { manage: await canManage(root, actor, document), publish: canPermission(document, actor, 'orgmaster.governance.publish'), simulate: canPermission(document, actor, 'orgmaster.governance.simulate') } }, current.revision); return }
  if (path === '/' && request.method === 'GET') { sendJson(response, 200, { document: sanitizedDocument(document), revision: current.revision, activeVersionId: document.activePolicyVersionId, versions: document.publishedVersions.map((v: any) => ({ id: v.id, versionNumber: v.versionNumber, publishedAt: v.publishedAt, publishedByPrincipalId: v.publishedByPrincipalId, publishReason: v.publishReason, snapshotHash: v.snapshotHash, organizationVersionId: v.organizationSnapshot.workspaceVersionId })) }, current.revision); return }
  if (path.startsWith('/versions/') && request.method === 'GET') { const id = decodeURIComponent(path.slice('/versions/'.length)); const version = document.publishedVersions.find((v) => v.id === id); if (!version) throw new GovernanceStoreError('POLICY_VERSION_NOT_FOUND'); sendJson(response, 200, { version: sanitizedDocument({ ...document, draft: document.draft, publishedVersions: [version] }).publishedVersions[0] }, current.revision); return }
  if (path === '/audit' && request.method === 'GET') { const audit = await readGovernanceAudit(root, Number(url.searchParams.get('limit') ?? 50), Number(url.searchParams.get('cursor') ?? 0)); sendJson(response, 200, audit, current.revision); return }
  if (path === '/draft' && request.method === 'PATCH') { const body = await parseBody(request); if (!await canManage(root, actor, document)) throw new GovernanceStoreError('GOVERNANCE_ADMIN_REQUIRED'); if (!revisionMatches(request, body, current.revision)) throw new GovernanceStoreError('REVISION_CONFLICT'); const candidate = body.command; if (!ensureCommandShape(candidate) || !['UPSERT_IDENTITY_LINK', 'SET_IDENTITY_LINK_STATUS', 'UPSERT_APPLICATION_ROLE', 'SET_APPLICATION_ROLE_STATUS', 'UPSERT_PERMISSION', 'SET_PERMISSION_STATUS', 'SET_ROLE_PERMISSION_GRANT', 'REMOVE_ROLE_PERMISSION_GRANT', 'UPSERT_ROLE_ASSIGNMENT', 'REVOKE_ROLE_ASSIGNMENT', 'UPSERT_DELEGATION', 'REVOKE_DELEGATION', 'UPSERT_APPROVAL_POLICY', 'SET_APPROVAL_POLICY_STATUS'].includes((candidate as GovernanceCommand).type)) throw new GovernanceStoreError('INVALID_JSON'); const result = await applyDraftCommand(root, current.revision, candidate as GovernanceCommand, actor); sendJson(response, 200, { status: result.status, document: sanitizedDocument(result.document), revision: result.revision }, result.revision); return }
  if (path === '/versions' && request.method === 'POST') { const body = await parseBody(request); if (!await canManage(root, actor, document)) throw new GovernanceStoreError('GOVERNANCE_ADMIN_REQUIRED'); if (!revisionMatches(request, body, current.revision)) throw new GovernanceStoreError('REVISION_CONFLICT'); const result = await publishGovernance(root, current.revision, String(body.commandId ?? ''), String(body.reason ?? ''), String(body.organizationVersionId ?? ''), actor); const version = result.document.publishedVersions.at(-1)!; sendJson(response, 201, { versionSummary: { id: version.id, versionNumber: version.versionNumber, publishedAt: version.publishedAt, snapshotHash: version.snapshotHash, organizationVersionId: version.organizationSnapshot.workspaceVersionId }, revision: result.revision }, result.revision); return }
  if (path === '/active-version' && request.method === 'POST') { const body = await parseBody(request); if (!await canManage(root, actor, document)) throw new GovernanceStoreError('GOVERNANCE_ADMIN_REQUIRED'); if (!revisionMatches(request, body, current.revision)) throw new GovernanceStoreError('REVISION_CONFLICT'); const result = await setActivePolicy(root, current.revision, String(body.commandId ?? ''), String(body.reason ?? ''), body.versionId === null ? null : String(body.versionId ?? ''), actor); sendJson(response, 200, { activePolicyVersionId: result.document.activePolicyVersionId, revision: result.revision }, result.revision); return }
  if (path === '/evaluate/permission' && request.method === 'POST') { const body = await parseBody(request); if (!(actor.bootstrap && !document.activePolicyVersionId) && !await canManage(root, actor, document)) throw new GovernanceStoreError('GOVERNANCE_ADMIN_REQUIRED'); const result = evaluatePermission(document, body as any, { timeSource: body.asOf ? 'local-simulator' : 'server' }); sendJson(response, 200, result, current.revision); return }
  if (path === '/evaluate/reviewers' && request.method === 'POST') { const body = await parseBody(request); if (!(actor.bootstrap && !document.activePolicyVersionId) && !await canManage(root, actor, document)) throw new GovernanceStoreError('GOVERNANCE_ADMIN_REQUIRED'); const result = resolveReviewers(document, body as any, { timeSource: body.asOf ? 'local-simulator' : 'server' }); sendJson(response, 200, result, current.revision); return }
  sendJson(response, 404, { error: 'ROUTE_NOT_FOUND' })
}
function middleware(root: string, devEnabled: boolean) { return (request: IncomingMessage, response: ServerResponse, next: Connect.NextFunction) => { if (!request.url?.startsWith(API_PATH)) return next(); void handle(request, response, root, devEnabled).catch((error) => errorResponse(response, error)) } }
export function orgmasterGovernanceApiPlugin(): Plugin { return { name: 'orgmaster-local-governance-api', configureServer(server: ViteDevServer) { server.middlewares.use(middleware(server.config.root, server.config.command === 'serve' && server.config.mode === 'development')) }, configurePreviewServer(server: PreviewServer) { server.middlewares.use(middleware(process.cwd(), false)) } } }
export { API_PATH }
