import { useState } from 'react'
import { evaluateGovernancePermission, resolveGovernanceReviewers } from '../governance/apiClient'
import type { PermissionEvaluationResultV1, ReviewerResolutionResultV1 } from '../governance/types'
export function GovernanceSimulator() {
  const [permissionCode, setPermissionCode] = useState('orgmaster.governance.manage'); const [actionCode, setActionCode] = useState('numbering.release'); const [result, setResult] = useState<PermissionEvaluationResultV1 | ReviewerResolutionResultV1 | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function runPermission() { setBusy(true); setError(''); try { setResult((await evaluateGovernancePermission({ applicationId: 'orgmaster', issuer: 'urn:orgmaster:dev', subject: 'local-admin', permissionCode, scope: { kind: 'global' } })).payload) } catch (e) { setError(e instanceof Error ? e.message : '測試失敗') } finally { setBusy(false) } }
  async function runReviewers() { setBusy(true); setError(''); try { setResult((await resolveGovernanceReviewers({ applicationId: 'ai-pdm', actionCode, requestor: { issuer: 'urn:orgmaster:dev', subject: 'local-admin' }, scope: { kind: 'global' } })).payload) } catch (e) { setError(e instanceof Error ? e.message : '測試失敗') } finally { setBusy(false) } }
  return <section className="governance-simulator" aria-labelledby="governance-simulator-title"><div className="governance-section-heading"><div><small>Ephemeral</small><h2 id="governance-simulator-title">政策測試器</h2></div><span className="governance-badge">不建立審核工作項</span></div><div className="governance-form-grid"><label>Permission code<input value={permissionCode} onChange={(e) => setPermissionCode(e.target.value)} /></label><button type="button" className="button button--primary" onClick={() => void runPermission()} disabled={busy}>測試權限</button><label>AI-PDM action code<input value={actionCode} onChange={(e) => setActionCode(e.target.value)} /></label><button type="button" className="button" onClick={() => void runReviewers()} disabled={busy}>解析審核人</button></div>{error && <p className="governance-error" role="alert">{error}</p>}{result && <pre className="governance-result" role="status">{JSON.stringify(result, null, 2)}</pre>}</section>
}
