import { useCallback, useEffect, useMemo, useState } from 'react'
import { ShieldCheck, RefreshCw, AlertTriangle } from 'lucide-react'
import { loadGovernance, loadGovernanceAudit, loadGovernanceSession, patchGovernanceDraft, publishGovernancePolicy, setActiveGovernanceVersion, validateGovernanceAssignment, type GovernanceApiSnapshot, type GovernanceSession } from '../governance/apiClient'
import { describeGovernanceFailure, governancePublishBlockersV2, type GovernanceFailureView } from '../governance/governancePresentation'
import { classifyAssignmentSurface, isSystemAdminRoleIdentity } from '../governance/assignmentSurface'
import type { GovernanceCommandV2, GovernanceRoleAssignmentV2, GovernanceRoleDelegationV2, ExternalRoleCatalogSnapshotV1 } from '../governance/types'
import type { Department, Employee, Role } from '../types'
import { GovernanceAssignmentCheck, type GovernanceAssignmentCheckResult } from './GovernanceAssignmentCheck'
import { GovernancePrivilegedAssignments } from './GovernancePrivilegedAssignments'
import './GovernanceCenter.css'

export type GovernanceSectionId = 'identity' | 'catalog' | 'assignments' | 'delegation' | 'versions' | 'audit' | 'check'
type Props = { employees: Employee[]; departments: Department[]; roles: Role[]; currentOrganizationVersionId: string | null; visibility?: 'active' | 'hidden'; initialSection?: GovernanceSectionId; onSectionChange?: (section: GovernanceSectionId) => void; workspaceMutationAllowed?: boolean; refreshToken?: number; onChanged?: () => void; onOpenEmployee?: (employeeId: string) => void }
type SectionId = GovernanceSectionId
const NAV: Array<{ id: SectionId; label: string }> = [
  { id: 'identity', label: '帳號治理' }, { id: 'catalog', label: '應用角色目錄' }, { id: 'assignments', label: '角色指派' }, { id: 'delegation', label: '角色代理' }, { id: 'versions', label: '發布版本' }, { id: 'audit', label: '稽核' }, { id: 'check', label: '指派檢查' },
]
const now = () => new Date().toISOString()
const activeAt = (status: string, from: string, to: string | null, at = now()) => status === 'active' && Date.parse(from) <= Date.parse(at) && (to === null || Date.parse(at) < Date.parse(to))
function employeeName(employees: Employee[], employeeId: string) { return employees.find((employee) => employee.id === employeeId)?.name ?? employeeId }
function accountTypeLabel(accountType?: string) { return accountType === 'human_personal' ? '日常帳號' : accountType === 'human_privileged' ? '特權帳號' : accountType === 'legacy_shared' ? '共用帳號' : accountType === 'service' ? '服務帳號' : '未分類' }
function scopeLabel(scope: GovernanceRoleAssignmentV2['scope']) { return scope.kind === 'global' ? '全域' : `${scope.kind}：${scope.value}` }
function roleLabel(catalogs: ExternalRoleCatalogSnapshotV1[], _draft: GovernanceApiSnapshot['document']['draft'], assignment: GovernanceRoleAssignmentV2) { if (assignment.applicationId === 'orgmaster') return assignment.roleNameSnapshot; return catalogs.flatMap((catalog) => catalog.roles).find((role) => role.stableRoleId === assignment.roleId)?.displayName ?? assignment.roleNameSnapshot }
function isPrivilegedSystemAdminAssignment(assignment: GovernanceRoleAssignmentV2) { return assignment.applicationId === 'ai-pdm' && (assignment.roleId === 'role-system-admin' || assignment.roleCodeSnapshot === 'system_admin') }

export function GovernanceCenter({ employees, departments, roles: _roles, currentOrganizationVersionId, visibility = 'active', initialSection = 'identity', onSectionChange, workspaceMutationAllowed = true, refreshToken = 0, onChanged, onOpenEmployee }: Props) {
  const [snapshot, setSnapshot] = useState<GovernanceApiSnapshot | null>(null)
  const [session, setSession] = useState<GovernanceSession | null>(null)
  const [revision, setRevision] = useState('')
  const [section, setSection] = useState<SectionId>(initialSection)
  const [failure, setFailure] = useState<GovernanceFailureView | null>(null)
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState(false)
  const [mobileReadOnly, setMobileReadOnly] = useState(false)
  const [audit, setAudit] = useState<Array<Record<string, unknown>>>([])
  const [assignmentEmployeeId, setAssignmentEmployeeId] = useState('')
  const [assignmentApplicationId, setAssignmentApplicationId] = useState<'ai-pdm' | 'orgmaster'>('ai-pdm')
  const [assignmentRoleId, setAssignmentRoleId] = useState('')
  const [assignmentScopeKind, setAssignmentScopeKind] = useState<'global' | 'workspace' | 'department' | 'project' | 'product'>('workspace')
  const [assignmentScopeValue, setAssignmentScopeValue] = useState('current')
  const [assignmentValidFrom, setAssignmentValidFrom] = useState(now().slice(0, 16))
  const [assignmentValidTo, setAssignmentValidTo] = useState('')
  const [delegationSourceId, setDelegationSourceId] = useState('')
  const [delegationToEmployeeId, setDelegationToEmployeeId] = useState('')
  const [delegationValidTo, setDelegationValidTo] = useState('')
  const [delegationReason, setDelegationReason] = useState('')
  const [publishReason, setPublishReason] = useState('')
  const [checkResult, setCheckResult] = useState<GovernanceAssignmentCheckResult | null>(null)

  const clearFeedback = useCallback(() => { setFailure(null); setNotice('') }, [])
  const recordFailure = useCallback((error: unknown) => { setNotice(''); setFailure(describeGovernanceFailure(error)) }, [])
  const refresh = useCallback(async (reset = true) => { if (reset) clearFeedback(); try { const [loaded, currentSession] = await Promise.all([loadGovernance(), loadGovernanceSession()]); setSnapshot(loaded.payload); setRevision(loaded.revision || loaded.payload.revision); setSession(currentSession.payload); return true } catch (error) { recordFailure(error); return false } }, [clearFeedback, recordFailure])
  useEffect(() => { if (visibility === 'hidden') return; void refresh() }, [refresh, refreshToken, visibility])
  useEffect(() => { const media = window.matchMedia('(max-width: 767px)'); const update = () => setMobileReadOnly(media.matches); update(); media.addEventListener('change', update); return () => media.removeEventListener('change', update) }, [])
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(''), 3200); return () => window.clearTimeout(timer) }, [notice])
  useEffect(() => setSection(initialSection), [initialSection])

  const document = snapshot?.document ?? { activePolicyVersionId: null }; const draft = snapshot?.document?.draft ?? null; const catalogs = snapshot?.catalogs ?? []; const catalog = catalogs.find((entry) => entry.applicationId === 'ai-pdm'); const actorPrincipalId = session?.actor.principalId ?? ''; const identityLinks = draft?.identityLinks ?? []; const currentIdentity = identityLinks.find((link) => link.principalId === actorPrincipalId && activeAt(link.status, link.validFrom, link.validTo)); const catalogReady = catalog?.validationState === 'valid'; const identityMutationAllowed = workspaceMutationAllowed && Boolean(session?.capabilities.manage) && !mobileReadOnly; const mutationAllowed = identityMutationAllowed && catalogReady
  const internalRoles = useMemo(() => draft?.applicationRoles.filter((role) => role.applicationId === 'orgmaster' && role.status === 'active') ?? [], [draft])
  const externalRoles = catalog?.roles.filter((role) => role.status === 'active') ?? []
  const selectableRoles = assignmentApplicationId === 'orgmaster' ? internalRoles.map((role) => ({ id: role.id, code: role.code, name: role.name, allowedScopeKinds: ['global'] as const })) : externalRoles.filter((role) => role.assignable).map((role) => ({ id: role.stableRoleId, code: role.code, name: role.displayName, allowedScopeKinds: role.allowedScopeKinds }))
  const roleAssignments = draft?.roleAssignments ?? []
  const ordinaryRoleAssignments = roleAssignments.filter((assignment) => !isPrivilegedSystemAdminAssignment(assignment))
  const selectedExternalRole = assignmentApplicationId === 'ai-pdm' ? externalRoles.find((role) => role.stableRoleId === assignmentRoleId) : undefined
  const selectedPrivilegedRole = assignmentApplicationId === 'ai-pdm' && isSystemAdminRoleIdentity(selectedExternalRole)
  const privilegedMode = selectedPrivilegedRole && classifyAssignmentSurface('ai-pdm', selectedExternalRole) === 'privileged_system_admin'
  const externalAssignments = roleAssignments.filter((assignment) => assignment.applicationId === 'ai-pdm' && assignment.status === 'active')
  const publishBlockers = draft && actorPrincipalId ? governancePublishBlockersV2(draft, actorPrincipalId, currentOrganizationVersionId) : []
  const publishMutationAllowed = mutationAllowed && Boolean(session?.capabilities.publish)
  const simulationAllowed = Boolean(session?.capabilities.simulate)

  useEffect(() => { if (!assignmentEmployeeId && currentIdentity) setAssignmentEmployeeId(currentIdentity.employeeId); if (!assignmentRoleId && selectableRoles[0]) setAssignmentRoleId(selectableRoles[0].id); if (assignmentRoleId && !selectableRoles.some((role) => role.id === assignmentRoleId)) setAssignmentRoleId(selectableRoles[0]?.id ?? ''); const selected = selectableRoles.find((role) => role.id === assignmentRoleId); if (selected && !selected.allowedScopeKinds.includes(assignmentScopeKind as never)) { const first = selected.allowedScopeKinds[0]; setAssignmentScopeKind(first); setAssignmentScopeValue(first === 'global' ? '' : first === 'workspace' ? 'current' : '') } }, [assignmentEmployeeId, assignmentRoleId, assignmentScopeKind, currentIdentity, selectableRoles])

  async function runCommand(command: GovernanceCommandV2, success: string) { setBusy(true); clearFeedback(); try { const result = await patchGovernanceDraft(revision, command); setSnapshot((current) => current ? { ...current, document: result.payload.document } : current); setRevision(result.revision || result.payload.revision); setNotice(result.payload.status === 'noop' ? '內容沒有變更' : success); onChanged?.(); return true } catch (error) { recordFailure(error); return false } finally { setBusy(false) } }
  function assignmentValue(): GovernanceRoleAssignmentV2 | null { if (!assignmentEmployeeId || !assignmentRoleId || !draft) return null; const selectedInternal = internalRoles.find((role) => role.id === assignmentRoleId); const selectedExternal = externalRoles.find((role) => role.stableRoleId === assignmentRoleId); if (assignmentApplicationId === 'orgmaster' && selectedInternal) return { id: draft.roleAssignments.find((value) => value.employeeId === assignmentEmployeeId && value.applicationId === 'orgmaster' && value.roleId === assignmentRoleId)?.id ?? `assignment-${crypto.randomUUID()}`, employeeId: assignmentEmployeeId, applicationId: 'orgmaster', roleId: selectedInternal.id, roleCodeSnapshot: selectedInternal.code, roleNameSnapshot: selectedInternal.name, catalogVersion: null, scope: { kind: 'global' }, status: 'active', validFrom: new Date(assignmentValidFrom).toISOString(), validTo: assignmentValidTo ? new Date(assignmentValidTo).toISOString() : null, effectState: 'orgmaster-enforced' }; if (!selectedExternal) return null; const effectiveScope = selectedExternal.allowedScopeKinds.includes('global') ? { kind: 'global' as const } : { kind: assignmentScopeKind as Exclude<typeof assignmentScopeKind, 'global'>, value: assignmentScopeValue }; const existingId = draft.roleAssignments.find((value) => value.employeeId === assignmentEmployeeId && value.applicationId === 'ai-pdm' && value.roleId === assignmentRoleId && value.scope.kind === effectiveScope.kind && (effectiveScope.kind === 'global' || (value.scope.kind !== 'global' && value.scope.value === effectiveScope.value)))?.id; return { id: existingId ?? `assignment-${crypto.randomUUID()}`, employeeId: assignmentEmployeeId, applicationId: 'ai-pdm', roleId: selectedExternal.stableRoleId, roleCodeSnapshot: selectedExternal.code, roleNameSnapshot: selectedExternal.displayName, catalogVersion: catalog?.catalogVersion ?? null, scope: effectiveScope, status: 'active', validFrom: new Date(assignmentValidFrom).toISOString(), validTo: assignmentValidTo ? new Date(assignmentValidTo).toISOString() : null, effectState: 'not-synchronized' } }
  async function submitAssignment() { const value = assignmentValue(); if (!value) { recordFailure({ code: 'GOVERNANCE_VALIDATION_FAILED', issues: [{ code: 'EXTERNAL_ROLE_UNKNOWN', message: '請選擇有效角色。' }] }); return } setBusy(true); clearFeedback(); try { const checked = await validateGovernanceAssignment(value); if (checked.payload.status !== 'valid') { recordFailure({ code: 'GOVERNANCE_VALIDATION_FAILED', issues: checked.payload.issues }); return } const ok = await runCommand({ type: 'UPSERT_ROLE_ASSIGNMENT', commandId: crypto.randomUUID(), reason: value.applicationId === 'ai-pdm' ? '建立外部應用角色指派' : '建立 OrgMaster 治理角色指派', value }, value.applicationId === 'ai-pdm' ? '角色已指派，尚未同步至目標系統' : 'OrgMaster 角色已指派'); if (ok) setCheckResult(checked.payload) } catch (error) { recordFailure(error) } finally { setBusy(false) } }
  function revokeAssignment(value: GovernanceRoleAssignmentV2) { void runCommand({ type: 'REVOKE_ROLE_ASSIGNMENT', commandId: crypto.randomUUID(), reason: '撤銷角色指派', id: value.id }, '角色指派已撤銷') }
  function submitDelegation() { const source = externalAssignments.find((value) => value.id === delegationSourceId); if (!source || !delegationToEmployeeId || !delegationValidTo || !delegationReason.trim()) { recordFailure({ code: 'ROLE_DELEGATION_INVALID' }); return } const value: GovernanceRoleDelegationV2 = { id: `delegation-${crypto.randomUUID()}`, sourceAssignmentId: source.id, fromEmployeeId: source.employeeId, toEmployeeId: delegationToEmployeeId, applicationId: 'ai-pdm', roleId: source.roleId, catalogVersion: source.catalogVersion!, scope: source.scope, status: 'active', validFrom: source.validFrom, validTo: new Date(delegationValidTo).toISOString(), reason: delegationReason.trim(), effectState: 'not-synchronized' }; void runCommand({ type: 'UPSERT_ROLE_DELEGATION', commandId: crypto.randomUUID(), reason: '建立角色代理', value }, '角色代理已建立，尚未同步至目標系統') }
  async function loadAudit() { try { const result = await loadGovernanceAudit(); setAudit(result.payload.items as Array<Record<string, unknown>>) } catch (error) { recordFailure(error) } }
  function changeSection(next: SectionId) { setSection(next); onSectionChange?.(next); clearFeedback(); if (next === 'audit') void loadAudit() }
  async function publish() { if (!currentOrganizationVersionId || !publishReason.trim() || publishBlockers.length) { recordFailure({ code: publishBlockers.length ? 'GOVERNANCE_VALIDATION_FAILED' : 'ORGANIZATION_VERSION_INVALID', issues: publishBlockers.map((blocker) => ({ code: blocker.code, message: blocker.message })) }); return } setBusy(true); clearFeedback(); try { const result = await publishGovernancePolicy(revision, crypto.randomUUID(), publishReason.trim(), currentOrganizationVersionId); await refresh(false); setPublishReason(''); setNotice(`已發布至 OrgMaster，尚未同步至目標系統（v${result.payload.versionSummary.versionNumber}）`) } catch (error) { recordFailure(error) } finally { setBusy(false) } }
  async function reactivate(versionId: string, versionNumber: number) { setBusy(true); try { await setActiveGovernanceVersion(revision, crypto.randomUUID(), '重新啟用角色指派版本', versionId); await refresh(false); setNotice(`角色指派版本 v${versionNumber} 已重新啟用`) } catch (error) { recordFailure(error) } finally { setBusy(false) } }
  async function checkAssignment() { const value = assignmentValue(); if (!value) return; setBusy(true); clearFeedback(); try { const result = await validateGovernanceAssignment(value); setCheckResult(result.payload); if (result.payload.status === 'valid') setNotice('指派檢查通過，尚未寫入治理資料') } catch (error) { recordFailure(error) } finally { setBusy(false) } }

  const content = <section className="governance-center governance-center--workspace" role="region" aria-labelledby="governance-title"><header className="governance-center__header"><div className="governance-title"><ShieldCheck size={22} aria-hidden="true" /><div><small>本機治理沙盒</small><h1 id="governance-title">角色指派治理</h1></div></div><div className="governance-center__status"><span className="governance-badge">尚未同步至外部系統</span><span>{draft ? `草稿 ${draft.updatedAt}` : '載入中'}</span></div></header><div className="governance-center__body"><nav className="governance-nav" aria-label="治理區段">{NAV.map((item) => <button type="button" key={item.id} className={section === item.id ? 'is-active' : ''} onClick={() => changeSection(item.id)}>{item.label}</button>)}</nav><main className="governance-main">{mobileReadOnly && <div className="governance-readonly" role="status">手機僅供閱讀</div>}{failure && <div className="governance-error" role="alert"><span>{failure.message}</span>{failure.canReload && <button type="button" className="button" onClick={() => void refresh()}>重新載入</button>}</div>}{notice && <div className="governance-notice" role="status">{notice}</div>}{!draft && !failure && <div className="governance-loading" role="status">載入治理資料…</div>}
{draft && section === 'identity' && <section className="governance-section"><SectionHeading eyebrow="Employee identity governance" title="帳號治理" count={`${identityLinks.length} 筆`} /><p className="governance-muted">這裡是跨員工檢視與異常定位；建立或管理登入身分請回到指定員工的「登入身分」明細。</p><div className="governance-table-wrap"><table className="governance-table"><thead><tr><th>登入身分</th><th>Employee</th><th>Issuer</th><th>帳號類型</th><th>狀態</th>{identityMutationAllowed && <th>操作</th>}</tr></thead><tbody>{identityLinks.map((link) => { const admission = draft.principalAdmissions?.find((candidate) => candidate.identityLinkId === link.id && candidate.status === 'active'); const isCurrent = link.principalId === actorPrincipalId; const canStatus = identityMutationAllowed && !admission && !isCurrent; return <tr key={link.id}><td>{link.subjectHint}<small>Principal {link.principalId}</small></td><td><button type="button" className="governance-employee-link" onClick={() => onOpenEmployee?.(link.employeeId)}>{employeeName(employees, link.employeeId)}</button></td><td>{link.issuer}</td><td>{accountTypeLabel(admission?.accountType)}</td><td>{link.status === 'active' ? '有效' : '停用'}</td>{identityMutationAllowed && <td>{canStatus ? <button type="button" className="button button--quiet" disabled={busy} onClick={() => void runCommand({ type: 'SET_IDENTITY_LINK_STATUS', commandId: crypto.randomUUID(), reason: link.status === 'active' ? '停用身分連結' : '重新啟用身分連結', id: link.id, status: link.status === 'active' ? 'inactive' : 'active' }, link.status === 'active' ? '身分連結已停用' : '身分連結已重新啟用')}>{link.status === 'active' ? '停用' : '重新啟用'}</button> : <small>{admission ? '已有帳號准入' : isCurrent ? '目前登入身分' : '唯讀'}</small>}</td>}</tr> })}</tbody></table></div>{!identityLinks.length && <p className="governance-empty">尚無已連結的登入身分；請從員工明細開始建立關係。</p>}</section>}
{draft && section === 'catalog' && <section className="governance-section"><SectionHeading eyebrow="External role catalog" title="應用角色目錄" count={`${(catalog?.roles.length ?? 0) + internalRoles.length} 筆`} /><div className="governance-source-note">AI-PDM · {catalog?.catalogVersion ?? '尚未取得'} · {catalog?.validationState === 'valid' ? '來源有效' : `來源${catalog?.validationState ?? '未知'}`} · 只讀</div><div className="governance-role-groups"><RoleGroup title="OrgMaster 自有角色" roles={internalRoles.map((role) => ({ id: role.id, name: role.name, code: role.code, risk: role.code === 'orgmaster_admin' ? 'high' : 'normal', assignable: true, scope: 'global' }))} /><RoleGroup title="AI-PDM 外部角色（唯讀）" roles={(catalog?.roles ?? []).map((role) => ({ id: role.stableRoleId, name: role.displayName, code: role.code, risk: role.riskLevel, assignable: role.assignable, scope: role.allowedScopeKinds.join('、') }))} /></div><p className="governance-muted">外部系統定義角色能力與權限細節；OrgMaster 只管理人員角色指派與治理狀態。</p></section>}
{draft && section === 'assignments' && <section className="governance-section"><SectionHeading eyebrow="Role assignments" title="角色指派" count={`${ordinaryRoleAssignments.length} 筆`} /><div className="governance-privileged__mode-switch"><label>切換角色<select aria-label="切換角色" value={assignmentRoleId} onChange={(event) => setAssignmentRoleId(event.target.value)} disabled={busy}>{selectableRoles.map((role) => <option key={role.id} value={role.id}>{role.name} · {role.code}</option>)}</select></label></div>{privilegedMode ? <GovernancePrivilegedAssignments employees={employees} workspaceMutationAllowed={workspaceMutationAllowed && !mobileReadOnly} onChanged={() => void refresh(false)} /> : selectedPrivilegedRole ? <div className="governance-privileged__state" role="alert"><strong>特權設定目前僅供閱讀</strong><p>system_admin 角色契約未完整符合目前目錄；已停用一般角色指派提交。</p></div> : <>{mutationAllowed && <AssignmentForm employees={employees} departments={departments} applicationId={assignmentApplicationId} onApplicationChange={(value) => { setAssignmentApplicationId(value); setAssignmentRoleId('') }} roleId={assignmentRoleId} roles={selectableRoles} employeeId={assignmentEmployeeId} onEmployeeChange={setAssignmentEmployeeId} scopeKind={assignmentScopeKind} scopeValue={assignmentScopeValue} onScopeKindChange={setAssignmentScopeKind} onScopeValueChange={setAssignmentScopeValue} validFrom={assignmentValidFrom} validTo={assignmentValidTo} onValidFrom={setAssignmentValidFrom} onValidTo={setAssignmentValidTo} onSubmit={() => void submitAssignment()} busy={busy} />}{ordinaryRoleAssignments.length ? <div className="governance-table-wrap"><table className="governance-table"><thead><tr><th>Employee</th><th>Application Role</th><th>Scope</th><th>期間</th><th>狀態</th>{mutationAllowed && <th>操作</th>}</tr></thead><tbody>{ordinaryRoleAssignments.map((assignment) => <tr key={assignment.id}><td>{employeeName(employees, assignment.employeeId)}</td><td>{roleLabel(catalogs, draft, assignment)}<small>{assignment.applicationId} · {assignment.roleCodeSnapshot}</small></td><td>{scopeLabel(assignment.scope)}</td><td>{assignment.validFrom.slice(0, 10)} ～ {assignment.validTo?.slice(0, 10) ?? '未設定'}</td><td>{assignment.status === 'active' ? '有效' : '已撤銷'}<small>{assignment.effectState === 'not-synchronized' ? '尚未同步' : 'OrgMaster enforced'}</small></td>{mutationAllowed && <td><button type="button" className="button button--quiet" disabled={busy} onClick={() => revokeAssignment(assignment)}>{assignment.status === 'active' ? '撤銷' : '已撤銷'}</button></td>}</tr>)}</tbody></table></div> : <p className="governance-empty">尚無一般角色指派</p>}</>}</section>}
{draft && section === 'delegation' && <section className="governance-section"><SectionHeading eyebrow="Role delegation" title="角色代理" count={`${draft.roleDelegations.length} 筆`} />{mutationAllowed && <div className="governance-assignment-form"><label>來源指派<select value={delegationSourceId} onChange={(event) => setDelegationSourceId(event.target.value)} disabled={busy}><option value="">選擇外部角色指派</option>{externalAssignments.map((assignment) => <option key={assignment.id} value={assignment.id}>{employeeName(employees, assignment.employeeId)} · {roleLabel(catalogs, draft, assignment)}</option>)}</select></label><label>代理員工<select value={delegationToEmployeeId} onChange={(event) => setDelegationToEmployeeId(event.target.value)} disabled={busy}><option value="">選擇員工</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select></label><label>代理截止<input type="datetime-local" value={delegationValidTo} onChange={(event) => setDelegationValidTo(event.target.value)} disabled={busy} /></label><label>原因<input value={delegationReason} onChange={(event) => setDelegationReason(event.target.value)} maxLength={240} disabled={busy} /></label><button type="button" className="button button--primary" onClick={submitDelegation} disabled={busy}>建立代理</button></div>}{draft.roleDelegations.length ? <div className="governance-card-grid">{draft.roleDelegations.map((delegation) => <article className="governance-card" key={delegation.id}><strong>{employeeName(employees, delegation.fromEmployeeId)} → {employeeName(employees, delegation.toEmployeeId)}</strong><small>{roleLabel(catalogs, draft, { ...delegation, roleCodeSnapshot: '', roleNameSnapshot: '', employeeId: delegation.fromEmployeeId, status: delegation.status } as GovernanceRoleAssignmentV2)} · {scopeLabel(delegation.scope)}</small><span>{delegation.validFrom.slice(0, 10)} ～ {delegation.validTo.slice(0, 10)} · 尚未同步</span></article>)}</div> : <p className="governance-empty">尚無角色代理</p>}</section>}
{draft && section === 'versions' && <section className="governance-section"><SectionHeading eyebrow="Immutable publication" title="發布版本" count={`${snapshot?.versions.length ?? 0} 筆`} />{publishMutationAllowed && <div className="governance-publish-box"><label>發布原因<input value={publishReason} onChange={(event) => setPublishReason(event.target.value)} maxLength={240} placeholder="說明本次角色指派治理變更" /></label><button type="button" className="button button--primary" onClick={() => void publish()} disabled={busy || publishBlockers.length > 0 || !publishReason.trim()}>發布角色指派版本</button></div>}{publishBlockers.length > 0 && <button type="button" className="governance-publish-readiness" onClick={() => changeSection(publishBlockers[0].section)}><AlertTriangle size={14} />發布前還有 {publishBlockers.length} 項設定</button>}<div className="governance-card-grid">{(snapshot?.versions ?? []).map((version) => <article className="governance-card governance-version" key={version.id}><strong>版本 v{version.versionNumber} · {version.kind === 'assignment-governance-v2' ? 'V2 指派治理' : '歷史 V1'}</strong><small>{version.publishedAt} · {version.organizationVersionId}</small><span>{version.effectState === 'not-synchronized' ? '尚未同步至外部系統' : '歷史版本'}</span>{document.activePolicyVersionId === version.id ? <span className="governance-version__active">目前生效</span> : publishMutationAllowed && version.kind === 'assignment-governance-v2' && <button type="button" className="button" onClick={() => void reactivate(version.id, version.versionNumber)} disabled={busy}>重新啟用</button>}</article>)}</div>{!snapshot?.versions.length && <p className="governance-empty">尚無發布版本</p>}</section>}
{draft && section === 'audit' && <section className="governance-section"><SectionHeading eyebrow="Governance change audit" title="稽核" count={`${audit.length} 筆`} /><button type="button" className="button" onClick={() => void loadAudit()}><RefreshCw size={14} />重新載入</button><div className="governance-table-wrap"><table className="governance-table"><thead><tr><th>時間</th><th>動作</th><th>Actor</th><th>Reason</th></tr></thead><tbody>{audit.map((event) => <tr key={String(event.id)}><td>{String(event.occurredAt)}</td><td>{String(event.action)}</td><td>{String(event.actorPrincipalId)}</td><td>{String(event.reason)}</td></tr>)}</tbody></table></div></section>}
{draft && section === 'check' && <section className="governance-section"><SectionHeading eyebrow="Candidate validation" title="指派檢查" count="不寫入" /><GovernanceAssignmentCheck result={checkResult} busy={busy} canCheck={simulationAllowed && Boolean(assignmentValue())} onCheck={() => void checkAssignment()} /></section>}
            </main></div></section>
  return content
}

function SectionHeading({ eyebrow, title, count }: { eyebrow: string; title: string; count: string }) { return <div className="governance-section-heading"><div><small>{eyebrow}</small><h2>{title}</h2></div><span>{count}</span></div> }
function RoleGroup({ title, roles }: { title: string; roles: Array<{ id: string; name: string; code: string; risk: string; assignable: boolean; scope: string }> }) { return <section className="governance-role-group"><h3>{title}</h3><div className="governance-card-grid">{roles.map((role) => <article className="governance-card" key={role.id}><strong>{role.name}</strong><small>{role.code} · {role.scope}</small><span className={role.risk === 'high' ? 'governance-risk governance-risk--high' : 'governance-risk'}>{role.risk === 'high' ? '高風險' : '一般'} · {role.assignable ? '可指派' : '不可指派'}</span></article>)}</div></section> }
function AssignmentForm({ employees, departments, applicationId, onApplicationChange, roles, roleId, employeeId, onEmployeeChange, scopeKind, scopeValue, onScopeKindChange, onScopeValueChange, validFrom, validTo, onValidFrom, onValidTo, onSubmit, busy }: { employees: Employee[]; departments: Department[]; applicationId: 'ai-pdm' | 'orgmaster'; onApplicationChange: (value: 'ai-pdm' | 'orgmaster') => void; roles: Array<{ id: string; code: string; name: string; allowedScopeKinds: readonly string[] }>; roleId: string; employeeId: string; onEmployeeChange: (value: string) => void; scopeKind: 'global' | 'workspace' | 'department' | 'project' | 'product'; scopeValue: string; onScopeKindChange: (value: 'global' | 'workspace' | 'department' | 'project' | 'product') => void; onScopeValueChange: (value: string) => void; validFrom: string; validTo: string; onValidFrom: (value: string) => void; onValidTo: (value: string) => void; onSubmit: () => void; busy: boolean }) { const selectedRole = roles.find((role) => role.id === roleId); const kinds = selectedRole?.allowedScopeKinds ?? []; return <form className="governance-assignment-form" onSubmit={(event) => { event.preventDefault(); onSubmit() }}><label>應用<select value={applicationId} onChange={(event) => onApplicationChange(event.target.value as 'ai-pdm' | 'orgmaster')} disabled={busy}><option value="ai-pdm">AI-PDM 外部角色</option><option value="orgmaster">OrgMaster 自有角色</option></select></label><label>員工<select value={employeeId} onChange={(event) => onEmployeeChange(event.target.value)} disabled={busy}><option value="">選擇員工</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select></label>{applicationId === 'orgmaster' ? <span className="governance-scope-chip">全域</span> : <><label>範圍<select value={scopeKind} onChange={(event) => onScopeKindChange(event.target.value as typeof scopeKind)} disabled={busy}>{kinds.map((kind) => <option key={kind} value={kind}>{kind}</option>)}</select></label>{scopeKind === 'department' ? <label>部門<select value={scopeValue} onChange={(event) => onScopeValueChange(event.target.value)} disabled={busy}><option value="">選擇部門</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></label> : scopeKind !== 'global' && <label>範圍值<input value={scopeValue} onChange={(event) => onScopeValueChange(event.target.value)} disabled={busy} /></label>}</>}<label>生效起日<input type="datetime-local" value={validFrom} onChange={(event) => onValidFrom(event.target.value)} disabled={busy} /></label><label>生效迄日（可選）<input type="datetime-local" value={validTo} onChange={(event) => onValidTo(event.target.value)} disabled={busy} /></label><button type="submit" className="button button--primary" disabled={busy || !employeeId || !roleId}>建立指派</button></form> }
