locals {
  app                            = "orgmaster"
  github_repository              = "jedchang0308-jenfu/OrgMaster"
  github_workflow_ref            = "jedchang0308-jenfu/OrgMaster/.github/workflows/deploy-orgmaster-independent-production.yml@refs/heads/master"
  pool_resource_name             = "projects/${data.google_project.current.number}/locations/global/workloadIdentityPools/${var.workload_identity_pool_id}"
  github_principal_set           = "principalSet://iam.googleapis.com/${local.pool_resource_name}/attribute.repository_id/${var.github_repository_id}"
  controller_service             = "orgmaster-prod-abort-controller"
  controller_audience            = "https://release-controller.jenfu.internal/orgmaster"
  controller_github_token_secret = "orgmaster-prod-controller-github-read-token"
  incident_topic                 = "orgmaster-prod-release-incident"
  candidate_smoke_workflow       = "orgmaster-prod-candidate-smoke"
  candidate_smoke_secret         = "orgmaster-prod-smoke-firebase-refresh-token"
  candidate_smoke_probe_path     = "/api/orgmaster/preferences/workbench"
  candidate_smoke_negative_path  = "/api/orgmaster/preferences/workbench"
  candidate_smoke_image_pattern  = "^asia-east1-docker\\.pkg\\.dev/jenfu-platform-prod/orgmaster-release/orgmaster@sha256:[a-f0-9]{64}$"
  receipt_prefix                 = "projects/_/buckets/${var.release_bucket_name}/objects/receipts/"
  control_prefix                 = "projects/_/buckets/${var.release_bucket_name}/objects/control/"
  source_prefix                  = "projects/_/buckets/${var.release_bucket_name}/objects/source/"
  logs_prefix                    = "projects/_/buckets/${var.release_bucket_name}/objects/logs/"
  labels                         = { owner = "orgmaster", contract = "dev-012", environment = "production" }
}
